#!/bin/sh

filename=$1
skbmark_file=$(pwd)/src/sockmark_define.h
iproute_file=$(pwd)/src/iproute_define.h

# clear output file
: > $filename

echo  "#!/bin/sh" >> $filename
echo  "##########################" >> $filename
echo  "# Automatically generated by rtk_base package: don't edit" >> $filename
echo  "# Provide other shell script source it." >> $filename
echo  "##########################" >> $filename
echo  "\n\n" >> $filename

echo  "##########################" >> $filename
echo  "# define ip route infomation from $(basename $iproute_file)" >> $filename
echo  "##########################" >> $filename
#awk -F' ' '($1~/^#define/) && ($2~/.*_RTL_TBL/) {print $2"="$3}' $iproute_file >> $filename
awk -F' ' '($1~/^#define/) && ($2~/^.*_RT_TBL/) {print $2"="$3}' $iproute_file >> $filename
echo  "\n\n" >> $filename
awk -F' ' '($1~/^#define/) && ($2~/^RULE_PRI_.*/) {print $2"="$3}' $iproute_file >> $filename


echo  "\n" >> $filename
echo  "##########################" >> $filename
echo  "# define skb mark infomation from $(basename $skbmark_file)" >> $filename
echo  "##########################" >> $filename
awk -F' ' '($1~/^#define/) && ($2~/^SOCK_MARK.*_START|END/) {print $2"="$3}' $skbmark_file >> $filename
