#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=60
USE_PROCD=1
PROCD_DEBUG=1

BIN=/usr/sbin/pptpd
CONFIG=/etc/pptpd.conf
PID_F=/var/run/pptpd.pid


start_service() {
	procd_open_instance
	#procd_set_param stdout 1
	#procd_set_param stderr 1
	procd_set_param command $BIN -c $CONFIG -p "$PID_F" --fg
	procd_close_instance
}

stop_service() {
	echo "pid file=$PID_F"
	if [ ! -e $PID_F ]; then
		return 1
	fi
	kill -9 `cat $PID_F`
	rm "$PID_F"
}

service_triggers () {
        procd_add_reload_trigger "pptpd"
}