#
# Copyright 2019 Shun Li <riverscn@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Realtek TR-369 configuration page
LUCI_DEPENDS:=+luci-compat +obuspa +libbbf_api +libbbfdm-openssl +uspd-openssl

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
