#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50
USE_PROCD=1
PROG=/usr/sbin/telnetd

start_service() {
	procd_open_instance
	procd_set_param command $PROG -l /bin/login
	procd_close_instance
}

