#!/bin/sh /etc/rc.common
# Copyright (C) 2015-2019 iopsys Software Solutions AB

START=99
STOP=00

USE_PROCD=1
PROG="/usr/sbin/icwmpd"

. /lib/functions.sh
. /usr/share/libubox/jshn.sh
include /lib/network

log() {
	echo "${@}"|logger -t cwmp.init -p info
}

regenerate_ssl_link()
{
	local cert_dir all_file rehash

	cert_dir="${1}"
	[ ! -d "${cert_dir}" ] && return 0;

	### Generate all ssl link for pem certicates ###
	all_file=$(ls $cert_dir/*.pem 2>/dev/null)
	if [ -n "${all_file}" ]; then
		for cfile in $all_file; do
			rehash="$(openssl x509 -hash -noout -in $cfile)"
			[ -f ${cert_dir}/${rehash}.0 ] || \
				ln -s $cfile $cert_dir/${rehash}.0
		done
	fi

	### Generate all ssl link for crt certicates ###
	all_file=$(ls $cert_dir/*.crt 2>/dev/null)
	if [ -n "${all_file}" ]; then
		for cfile in $all_file; do
			rehash="$(openssl x509 -hash -noout -in $cfile)"
			[ -f ${cert_dir}/${rehash}.0 ] || \
				ln -s $cfile $cert_dir/${rehash}.0
		done
	fi
}

enable_dhcp_option43() {
	local wan="${1}"

	### Ask for DHCP Option 43 only if CWMP is enabled ###
	local reqopts="$(uci -q get network.$wan.reqopts)"
	local proto="$(uci -q get network.$wan.proto)"
	local newreqopts=""
	local option43_present=0

	for ropt in $reqopts; do
		case $ropt in
			43) option43_present=1 ;;
			*) ;;
		esac
	done

	if [ ${option43_present} -eq 1 ]; then
		return;
	fi

	newreqopts="$reqopts 43"
	if [ "${proto}" == "dhcp" ]; then
		uci -q set network.$wan.reqopts="$newreqopts"
		uci commit network
		ubus call network reload
	fi
}

convert_to_hex() {
	local val=""
	local optval="${1}"
	OPTIND=1
	while getopts ":" opt "-$optval"
	do
		temp=$(printf "%X" "'${OPTARG:-:}")
		val="${val}:${temp}"
	done

	echo "${val}"
}

configure_send_op125() {
	local sendopt="${1}"
	local intf="${2}"
	local uci="${3}"
	local hex_oui=""
	local hex_serial=""
	local hex_class=""
	local oui_len=0
	local serial_len=0
	local class_len=0

	if [ "${uci}" = "network" ]; then
		local opt125="125:00:00:0D:E9"
	else
		local opt125="125,00:00:0D:E9"
	fi

	config_get oui cpe manufacturer_oui ""
	if [ -z "${oui}" ]; then
		oui=$(db -q get device.deviceinfo.ManufacturerOUI)
	fi

	oui=$(echo "${oui}" | tr 'a-f' 'A-F')

	config_get serial cpe serial_number ""
	if [ -z "${serial}" ]; then
		serial=$(db -q get device.deviceinfo.SerialNumber)
	fi

	config_get class cpe product_class ""
	if [ -z "${class}" ]; then
		class=$(db -q get device.deviceinfo.ProductClass)
	fi

	oui_len=$(echo -n "${oui}" | wc -m)
	serial_len=$(echo -n "${serial}" | wc -m)
	class_len=$(echo -n "${class}" | wc -m)

	if [ ${oui_len} -eq 0 ] || [ ${serial_len} -eq 0 ]; then
		return 0
	fi

	opt125_len=$((oui_len + serial_len + class_len))
	if [ ${class_len} -gt 0 ]; then
		opt125_len=$((opt125_len + 6))
	else
		opt125_len=$((opt125_len + 4))
	fi

	hex_opt125_len=$(printf "%X" "${opt125_len}")
	opt125="${opt125}:${hex_opt125_len}"
	hex_oui=$(convert_to_hex "${oui}")
	if [ -z "${hex_oui}" ]; then
		return 0
	fi

	hex_oui_len=$(printf "%X" "${oui_len}")
	if [ "${uci}" = "network" ]; then
		opt125="${opt125}:01:${hex_oui_len}${hex_oui}"
	else
		opt125="${opt125}:04:${hex_oui_len}${hex_oui}"
	fi

	hex_serial=$(convert_to_hex "${serial}")
	if [ -z "${hex_serial}" ]; then
		return 0
	fi

	hex_serial_len=$(printf "%X" "${serial_len}")
	if [ "${uci}" = "network" ]; then
		opt125="${opt125}:02:${hex_serial_len}${hex_serial}"
	else
		opt125="${opt125}:05:${hex_serial_len}${hex_serial}"
	fi

	if [ ${class_len} -gt 0 ]; then
		hex_class=$(convert_to_hex "${class}")
		if [ -z "${hex_class}" ]; then
			return 0
		fi

		hex_class_len=$(printf "%X" "${class_len}")
		if [ "${uci}" = "network" ]; then
			opt125="${opt125}:03:${hex_class_len}${hex_class}"
		else
			opt125="${opt125}:06:${hex_class_len}${hex_class}"
		fi
	fi


	if [ "${uci}" = "network" ]; then
		new_send_opt="$sendopt $opt125"
		uci -q set network.$intf.sendopts="$new_send_opt"
	else
		uci -q add_list dhcp.$intf.dhcp_option="$opt125"
	fi
}

enable_dnsmasq_option125() {
	local lan="${1}"
	local send125_present=0
	local opt125="125,"

	local proto="$(uci -q get dhcp.$lan.dhcpv4)"
	if [ "${proto}" = "server" ]; then
		opt_list="$(uci -q get dhcp.$lan.dhcp_option)"

		for sopt in $opt_list; do
			if [[ "$sopt" == "$opt125"* ]]; then
				send125_present=1
				break
			fi
		done

		if [ ${send125_present} -eq 0 ]; then
			configure_send_op125 "" "${lan}" "dhcp"
			ubus call uci commit '{"config":"dhcp"}'
		fi
	fi
}

enable_disable_dhcp_option125() {
	local wan="${1}"
	local action="${2}"

	local reqopts="$(uci -q get network.$wan.reqopts)"
	local sendopts="$(uci -q get network.$wan.sendopts)"
	local proto="$(uci -q get network.$wan.proto)"
	local newreqopts=""
	local newsendopts=""
	local req125_present=0
	local send125_present=0
	local network_uci_update=0
	local opt125="125:"

	for ropt in $reqopts; do
		case $ropt in
			125) req125_present=1 ;;
			*) ;;
		esac
	done

	for sopt in $sendopts; do
		if [[ "$sopt" == "$opt125"* ]]; then
			send125_present=1
			break
		fi
	done

	if [ "${proto}" == "dhcp" ]; then
		if [ "${action}" == "enable" ]; then
			if [ ${req125_present} -eq 0 ]; then
				newreqopts="$reqopts 125"
				uci -q set network.$wan.reqopts="$newreqopts"
				network_uci_update=1
			fi

			if [ ${send125_present} -eq 0 ]; then
				configure_send_op125 "${sendopts}" "${wan}" "network"
				network_uci_update=1
			fi
		else
			if [ ${req125_present} -eq 1 ]; then
				newreqopts=$(echo ${reqopts/125/})
				uci -q set network.$wan.reqopts="$newreqopts"
				network_uci_update=1
			fi

			if [ ${send125_present} -eq 1 ]; then
				for sopt in $sendopts; do
					if [[ "$sopt" == "$opt125"* ]]; then
						newsendopts=$(echo ${sendopts/"${sopt}"/})
						uci -q set network.$wan.sendopts="$newreqopts"
						network_uci_update=1
						break
					fi
				done
			fi
		fi
	fi

	if [ ${network_uci_update} -eq 1 ]; then
		uci commit network
		ubus call network reload
	fi
}

wait_for_resolvfile() {
	local time=$1
	local tm=1

	local resolvfile="$(uci -q get dhcp.@dnsmasq[0].resolvfile)"
	[ -n "$resolvfile" ] || return

	while [ ! -f "$resolvfile" ]; do
		sleep 1
		[ "$tm" -ge "$time" ] && break
		tm=$((tm+1))
	done
}

copy_cwmp_etc_files_to_varstate() {
	mkdir -p /var/run/icwmpd

	if [ -f /etc/icwmpd/cwmp ]; then
		uci -q -c /etc/icwmpd delete cwmp.acs
		uci -q -c /etc/icwmpd commit cwmp
		cp -f /etc/icwmpd/cwmp /var/state/cwmp
	fi

	#if [ -f /etc/icwmpd/icwmpd_backup_session.xml ]; then
	#	cp -f /etc/icwmpd/icwmpd_backup_session.xml /var/run/icwmpd/ 2>/dev/null
	#fi

	if [ -f /etc/icwmpd/dm_enabled_notify.xml ]; then
		cp -f /etc/icwmpd/dm_enabled_notify /var/run/icwmpd/ 2>/dev/null
	fi
}

copy_cwmp_varstate_files_to_etc() {
	#if [ -f /var/run/icwmpd/icwmpd_backup_session.xml ]; then
	#	cp -f /var/run/icwmpd/icwmpd_backup_session.xml /etc/icwmpd/ 2>/dev/null
	#fi

	if [ -f /var/run/icwmpd/dm_enabled_notify.xml ]; then
		cp -f /var/run/icwmpd/dm_enabled_notify /etc/icwmpd/ 2>/dev/null
	fi

	if [ -f /var/state/cwmp ]; then
		cp -f /var/state/cwmp /etc/icwmpd/
	fi

	# move the successful custom notify import marker to persistent storage
	if [ -f /var/run/icwmpd/icwmpd_notify_import_marker ]; then
		cp -f /var/run/icwmpd/icwmpd_notify_import_marker /etc/icwmpd/
	fi
}

validate_acs_section()
{
	uci_validate_section cwmp acs "acs" \
		'passwd:string' \
		'periodic_inform_enable:bool' \
		'periodic_inform_interval:uinteger' \
		'periodic_inform_time:string' \
		'url:string' \
		'dhcp_discovery:string' \
		'dhcp_url:string' \
		'compression:or("GZIP","Deflate","Disabled")' \
		'retry_min_wait_interval:range(1, 65535)' \
		'retry_interval_multiplier:range(1000, 65535)' \
		'ipv6_enable:bool' \
		'ssl_capath:string'

}

validate_cpe_section()
{
	uci_validate_section cwmp cpe "cpe" \
		'interface:string' \
		'default_wan_interface:string' \
		'log_to_console:or("enable","disable")' \
		'log_to_file:or("enable","disable")' \
		'log_severity:or("EMERG", "ALERT", "CRITIC" ,"ERROR", "WARNING", "NOTICE", "INFO", "DEBUG")' \
		'log_file_name:string' \
		'log_max_size:uinteger' \
		'userid:string' \
		'passwd:string' \
		'port:uinteger' \
		'provisioning_code:string:""' \
		'amd_version:range(1, 6)' \
		'instance_mode:or("InstanceNumber","InstanceAlias")' \
		'session_timeout:uinteger' \
		'notification:bool' \
		'exec_download:bool' \
		'periodic_notify_enable:bool' \
		'enable:bool' \
		'periodic_notify_interval:uinteger'
}

validate_defaults() {
	local ssl_capath
	config_load cwmp

	validate_acs_section || {
		log "Validation of acs section failed"
		return 1;
	}

	ssl_capath="${ssl_capath%/}"
	# Put the cert pem file in keep list
	if [ -d "${ssl_capath}" ]; then
		if ! grep "*.pem\|*.crt" /lib/upgrade/keep.d/icwmp; then
			echo "${ssl_capath}"'/*.pem' >> /lib/upgrade/keep.d/icwmp
			echo "${ssl_capath}"'/*.crt' >> /lib/upgrade/keep.d/icwmp
			echo "${ssl_capath}"'/*.0' >> /lib/upgrade/keep.d/icwmp
		fi
	fi

	validate_cpe_section || {
		log "Validation of cpe section failed"
		return 1;
	}

	return 0;
}

boot() {
	local dhcp_discovery="0"

	config_load cwmp
	config_get dhcp_discovery acs dhcp_discovery "0"

	config_get wan_interface cpe default_wan_interface "wan"
	if [ "${dhcp_discovery}" == "enable" ] || [ "${dhcp_discovery}" == "1" ]; then
		# Set dhcp option 43 if not already configured
		enable_dhcp_option43 "${wan_interface}"
	fi

	config_get lan_interface cpe default_lan_interface ""
	if [ -n "${lan_interface}" ]; then
		# Set dhcp_option 125 if not already configured
		enable_disable_dhcp_option125 "${wan_interface}" "enable"
		enable_dnsmasq_option125 "${lan_interface}"
	else
		# Remove dhcp option 125 if exists
		enable_disable_dhcp_option125 "${wan_interface}" "disable"
	fi
	
	config_get ssl_capath acs ssl_capath

	if [ -n "${ssl_capath}" ]; then
		regenerate_ssl_link "${ssl_capath}"
	fi

	start
}

start_service() {
	local enable_cwmp

	config_load cwmp
	config_get_bool enable_cwmp cpe enable 1

	if [ "$enable_cwmp" = "0" ]; then
		return 0
	fi

	[ -f /sbin/netifd ] && log "Waiting for Network to be started ..." && ubus -t 5 wait_for network.interface
	[ -f /usr/sbin/dnsmasq ] && log "Waiting for DNS Proxy to be started ..." && ubus -t 5 wait_for dnsmasq
	[ -f /etc/config/dhcp ] && log "Waiting for DNS Server(s) ..." && wait_for_resolvfile 20

	validate_defaults || {
		log "Validation of defaults failed"
		return 1;
	}

	# Copy backup data so that if it restart latter on it gets the info
	copy_cwmp_etc_files_to_varstate

	procd_open_instance icwmp
	procd_set_param command "$PROG"
	procd_append_param command -b
	procd_set_param respawn \
		"${respawn_threshold:-5}" \
		"${respawn_timeout:-10}" "${respawn_retry:-3}"

	procd_set_param watch network.interface
	procd_close_instance
}

service_stopped()
{
	copy_cwmp_varstate_files_to_etc
}

reload_service() {
	local ret

	config_load cwmp
	config_get_bool enable_cwmp cpe enable 1

	ret="0"
	if [ "$enable_cwmp" = "0" ]; then
		stop
		start
		return 0
	fi

	status="$(ubus -t 1 call tr069 status |jsonfilter -qe '@.cwmp.status')"
	ret="$?"
	if [ "$status" = "up" ]; then
		ubus -t 1 call tr069 command '{"command":"reload"}'
		ret="$?"
	fi

	if [ "$status" = "init" ] || [ "$ret" -ne "0" ]; then
		log "Restarting CWMP client"
		stop
		start
	fi
}

service_triggers() {
       procd_add_reload_trigger "cwmp"

       procd_open_trigger
               json_add_array
                       json_add_string "" "interface.update"
                       json_add_array
                               json_add_array
                                       json_add_string "" "run_script"
                                       json_add_string "" "/etc/icwmpd/update.sh"
                               json_close_array
                       json_close_array
                       json_add_int "" "2000"
               json_close_array
       procd_close_trigger
}

