deps_config := \
	feeds/packages/utils/yara/Config.in \
	feeds/packages/utils/mc/Config.in \
	rtk_openwrt/feeds/map-topology/Config.in \
	feeds/packages/utils/lxc/Config.in \
	feeds/packages/utils/lcd4linux/Config.in \
	package/boot/kexec-tools/Config.in \
	feeds/packages/utils/haserl/Config.in \
	feeds/packages/utils/dockerd/Config.in \
	feeds/packages/utils/dbus/Config.in \
	rtk_openwrt/feeds/bbf/Config_bbfdm.in \
	rtk_openwrt/feeds/ieee1905/Config.map-plugin.in \
	rtk_openwrt/feeds/ieee1905/Config.in \
	feeds/packages/utils/squashfs-tools/Config.in \
	feeds/packages/utils/btrfs-progs/Config.in \
	feeds/packages/utils/parted/Config.in \
	feeds/packages/libs/sqlite3/Config-cli.in \
	feeds/packages/sound/upmpdcli/Config.in \
	feeds/packages/sound/lame/Config.in \
	feeds/packages/sound/fdk-aac/Config.in \
	rtk_openwrt/package/realtek/rtk_igmpproxy/Config.in \
	rtk_openwrt/package/realtek/rtk_base/Config.in \
	rtk_openwrt/package/realtek/multi-ap_release_ap/Config.in \
	rtk_openwrt/package/realtek/librtk_timerlist/Config.in \
	feeds/packages/net/samba4/Config.in \
	feeds/packages/net/nut/Config.in \
	feeds/packages/net/mstpd/Config.in \
	feeds/packages/net/mosquitto/Config.in \
	feeds/packages/net/modemmanager/Config.in \
	feeds/packages/net/keepalived/Config.in \
	feeds/packages/net/iputils/Config_tracepath.in \
	feeds/packages/net/iputils/Config_ping.in \
	feeds/packages/net/ifstat/Config.in \
	feeds/packages/net/gensio/Config-bin.in \
	feeds/packages/net/bwm-ng/Config.in \
	feeds/routing/alfred/Config.in \
	package/network/services/hostapd/Config.in \
	feeds/packages/net/aircrack-ng/Config.in \
	feeds/packages/net/squid/Config.in \
	feeds/packages/net/privoxy/Config.in \
	feeds/packages/net/nginx/Config_ssl.in \
	feeds/packages/net/zerotier/Config.in \
	feeds/packages/net/vpnc/Config.in \
	rtk_openwrt/feeds/strongswan/Config.in \
	feeds/packages/net/openvpn/Config-wolfssl.in \
	feeds/packages/net/openvpn/Config-openssl.in \
	feeds/packages/net/openvpn/Config-mbedtls.in \
	feeds/packages/net/openconnect/Config.in \
	feeds/packages/net/ocserv/Config.in \
	feeds/packages/net/fastd/Config.in \
	feeds/telephony/net/freeswitch/Config.in \
	feeds/packages/net/openssh/Config.in \
	package/network/services/lldpd/Config.in \
	feeds/packages/net/frr/Config.in \
	feeds/packages/net/openvswitch/Config.in \
	feeds/routing/oonf-olsrd2/Config.in \
	feeds/packages/net/znc/Config.in \
	feeds/packages/net/knot-resolver/Config.in \
	feeds/packages/net/kadnode/Config.in \
	feeds/packages/net/dnscrypt-proxy/Config.in \
	feeds/packages/net/bind/Config.in \
	feeds/packages/net/freeradius3/Config.in \
	feeds/packages/net/snort/Config.in \
	feeds/packages/net/fwknop/Config.in \
	feeds/packages/net/nfs-kernel-server/Config.in \
	feeds/packages/net/rsync/Config.in \
	feeds/packages/net/aria2/Config.in \
	feeds/packages/net/coova-chilli/Config.in \
	feeds/packages/multimedia/tvheadend/Config.in \
	feeds/packages/multimedia/gst1-libav/Config.in \
	feeds/packages/mail/mutt/Config.in \
	feeds/packages/mail/fdm/Config.in \
	feeds/packages/mail/dovecot/Config.in \
	package/libs/zlib/Config.in \
	feeds/packages/libs/libtins/Config.in \
	feeds/packages/libs/libstrophe/Config.in \
	feeds/packages/libs/libqmi/Config.in \
	feeds/packages/libs/pcre2/Config.in \
	package/libs/pcre/Config.in \
	package/libs/libpcap/Config.in \
	package/libs/nettle/Config.in \
	feeds/packages/net/lora-gateway-hal/Config.in \
	feeds/packages/net/gensio/Config.in \
	feeds/packages/multimedia/ffmpeg/Config.in \
	feeds/packages/libs/libdvbcsa/Config.in \
	feeds/packages/libs/libdrm/Config.in \
	feeds/packages/net/curl/Config.in \
	feeds/packages/libs/getdns/Config.in \
	package/libs/wolfssl/Config.in \
	feeds/packages/libs/afalg_engine/Config.in \
	package/libs/openssl/Config.in \
	feeds/packages/libs/gnutls/Config.in \
	rtk_openwrt/feeds/easy-soc-libs/Config.in \
	feeds/packages/utils/owfs/Config.in \
	feeds/packages/libs/sqlite3/Config-lib.in \
	feeds/packages/libs/libpqxx/Config.in \
	feeds/packages/libs/liblz4/Config.in \
	feeds/packages/lang/python/pymysql/Config.in \
	feeds/packages/lang/python/python3/Config-python3-light.in \
	feeds/packages/lang/perl/Config.in \
	feeds/packages/lang/luv/Config.in \
	feeds/packages/lang/golang/golang/Config.in \
	rtk_openwrt/package/kernel/realtek/rtk_wifi6_ap/Kconfig.openwrt \
	rtk_openwrt/package/kernel/realtek/rtk_wifi6_ap/Config.in \
	rtk_openwrt/package/kernel/realtek/rtk_wifi6/Config.in \
	package/kernel/lantiq/ltq-vmmc/Config.in \
	package/kernel/lantiq/ltq-tapi/Config.in \
	feeds/routing/batman-adv/Config.in \
	feeds/packages/devel/gcc/Config.in \
	feeds/packages/admin/schroot/Config.in \
	feeds/packages/admin/rsyslog/Config.in \
	package/network/services/dropbear/Config.in \
	package/utils/busybox/config/sysklogd/Config.in \
	package/utils/busybox/config/shell/Config.in \
	package/utils/busybox/config/selinux/Config.in \
	package/utils/busybox/config/runit/Config.in \
	package/utils/busybox/config/procps/Config.in \
	package/utils/busybox/config/mailutils/Config.in \
	package/utils/busybox/config/printutils/Config.in \
	package/utils/busybox/config/networking/udhcp/Config.in \
	package/utils/busybox/config/networking/Config.in \
	package/utils/busybox/config/miscutils/Config.in \
	package/utils/busybox/config/util-linux/volume_id/Config.in \
	package/utils/busybox/config/util-linux/Config.in \
	package/utils/busybox/config/modutils/Config.in \
	package/utils/busybox/config/e2fsprogs/Config.in \
	package/utils/busybox/config/loginutils/Config.in \
	package/utils/busybox/config/init/Config.in \
	package/utils/busybox/config/findutils/Config.in \
	package/utils/busybox/config/editors/Config.in \
	package/utils/busybox/config/klibc-utils/Config.in \
	package/utils/busybox/config/debianutils/Config.in \
	package/utils/busybox/config/console-tools/Config.in \
	package/utils/busybox/config/coreutils/Config.in \
	package/utils/busybox/config/archival/Config.in \
	package/utils/busybox/config/libbb/Config.in \
	package/utils/busybox/config/Config.in \
	package/utils/busybox/Config-defaults.in \
	package/utils/busybox/Config.in \
	tmp/.config-feeds.in \
	package/base-files/image-config.in \
	tmp/.config-package.in \
	target/toolchain/Config.in \
	target/sdk/Config.in \
	target/imagebuilder/Config.in \
	toolchain/gcc/Config.version \
	toolchain/binutils/Config.version \
	toolchain/musl/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/Config.in \
	config/Config-devel.in \
	config/Config-kernel.in \
	config/Config-build.in \
	target/linux/sunxi/image/Config.in \
	target/linux/realtek_bb/image/Config.in \
	target/linux/omap/image/Config.in \
	target/linux/mxs/image/Config.in \
	target/linux/at91/image/Config.in \
	target/linux/archs38/image/Config.in \
	config/Config-images.in \
	tmp/.config-target.in \
	target/Config.in \
	Config.in

include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
