include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-rtk-mcproxy
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for mcproxy
LUCI_DEPENDS:=+mcproxy
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
