#!/bin/sh /etc/rc.common

START=99

PNAME=map_checker
PROG=/bin/map_checker
DEBUG=1
USE_PROCD=1
MAP_ROLE_DISABLE=0
MAP_ROLE_CONTROLLER=1
MAP_ROLE_AGENT=2

W_LOG()
{
	if [ $DEBUG -eq 1 ]; then
		echo "[${PNAME}] $@" > /dev/console
	fi
}

W_ERR()
{
	if [ $DEBUG -eq 1 ]; then
		echo "[${PNAME}][ERR] $@" > /dev/console
	fi
}

start_service()
{
	W_LOG "Start service ..."

	local profile controller log_level
	config_load "rtkmap"
	config_get profile "map" "profile"
	config_get controller "map" "controller"
	config_get log_level "map" "log_level"

	if [ "$controller" -eq $MAP_ROLE_DISABLE ]; then
		W_LOG "MAP disabled, exit."
		return
	fi

	local let i=0
	local log_level_s=""
	while [ $i -lt $log_level ]; do
		log_level_s=$log_level_s"v"
		let i=i+1
	done
	[ ! -z "$log_level_s" ] && log_level_s="-"$log_level_s

	local cmd args
	args="$log_level_s -p$profile"
	cmd="map_checker $args"

	if [ ! -z "$cmd" ]; then
		procd_open_instance
		procd_set_param respawn ${threshold:-3600} ${timeout:-5} ${retry:-5}
		procd_set_param command /bin/sh -c "$cmd"
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
}

stop_service()
{
	W_LOG "Stop service."
}

reload_service() {
	stop
	start
}

service_triggers() {
	PROCD_RELOAD_DELAY=2000
	procd_add_reload_trigger "rtkmap"
}
