#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=xl2tpd
RUN_D=/var/run/xl2tpd
PID_F=$RUN_D/xl2tpd.pid
CONFIG=$RUN_D/xl2tpd.conf
L2TP_SECRETS=$RUN_D/l2tp-secrets      # l2tp tunnel auth secrets file
LNS_OPTIONS_FILE=$RUN_D/options.x2ltpd_lns
PPP_CHAP_SECRETS=/var/run/chap-secrets      # default ppp secrets file path
FW_SCRIPT=/usr/share/xl2tpd/firewall.include
SECRET_NAME=l2tp-server

CONFIG_BASE=/etc/xl2tpd/xl2tpd.conf
L2TP_SECRET_BASE=/etc/xl2tpd/xl2tp-secrets
LNS_OPTIONS_BASE=/etc/ppp/options.xl2tpd_lns

validate_login_section() {
	uci_load_validate xl2tpd login "$1" "$2" \
		'username:string' \
		'password:string' \
		'remoteip:string'
}

validate_xl2tpd_section() {
	uci_load_validate xl2tpd service "$1" "$2" \
		'enabled:uinteger:0' \
		'localip:string' \
		'remoteip:string' \
		'auth:uinteger:0' \
		'authmode:string' \
		'mppe:string' \
		'logwtmp:uinteger:0'
}

remove_login() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	[ -n "$username" ] || return 1
	[ -n "$password" ] || return 1
	[ -n "$remoteip" ] || remoteip=*

	# Remove PPTPD secret
	sed -i "/$username $SECRET_NAME $password $remoteip/d" $PPP_CHAP_SECRETS
}

setup_login() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	[ -n "$username" ] || return 1
	[ -n "$password" ] || return 1
	[ -n "$remoteip" ] || remoteip=*

	# Remove PPTPD secret
	sed -i "/$username $SECRET_NAME $password $remoteip/d" $PPP_CHAP_SECRETS
	echo "$username $SECRET_NAME $password $remoteip" >> $PPP_CHAP_SECRETS
}

setup_config() {
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	# remove firewall rule
	if [ $enabled -eq 0 ]; then
		local fw_rule
		config_load firewall
		config_get fw_rule xl2tpd enabled
		if [ $fw_rule -ne 0 ]; then
			uci set firewall.xl2tpd.enabled=0
			uci commit
			fw3 reload
		fi
		return 0
	fi

	cp $CONFIG_BASE $CONFIG
	cp $L2TP_SECRET_BASE $L2TP_SECRETS
	cp $LNS_OPTIONS_BASE $LNS_OPTIONS_FILE

	echo "[lns default]" >> $CONFIG
	[ -n "$localip" ] && echo "local ip = $localip" >> $CONFIG
	[ -n "$remoteip" ] && echo "ip range = $remoteip" >> $CONFIG
	echo "pppoptfile = $LNS_OPTIONS_FILE" >> $CONFIG
	if [ -n "$l2tpAuth" ]; then
		echo "require authentication = yes" >> $CONFIG
		echo "auth file = $L2TP_AUTH_SECRET" >> $CONFIG
	fi

	if [ $auth -eq 1 ]; then
		echo "auth" >> $LNS_OPTIONS_FILE
		[ -n "$authmode" ] && echo "$authmode" >> $LNS_OPTIONS_FILE
		[ -n "$mppe" ] && echo "$mppe" >> $LNS_OPTIONS_FILE
	fi
	echo "ms-dns $localip" >> $LNS_OPTIONS_FILE

	return 0
}

start_service() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"
	local enabled
	config_load xl2tpd
	config_get enabled xl2tpd enabled
	validate_xl2tpd_section xl2tpd setup_config || return
	config_foreach validate_login_section login setup_login

	if [ $enabled -eq 1 ]; then
		echo "[`date`] LNS mode" >> /tmp/l2tp_dbg
		ln -sfn $PPP_CHAP_SECRETS /etc/ppp/chap-secrets

		# start firewall
		local fw_rule
		config_load firewall
		config_get fw_rule xl2tpd enabled
		if [ $fw_rule -ne 1 ]; then
			uci -q set firewall.xl2tpd.enabled=1
			uci commit
			fw3 reload
		fi

		procd_open_instance
		procd_set_param command $BIN -D -l -c $CONFIG -s $L2TP_SECRETS -p $PID_F
		procd_set_param respawn
		procd_close_instance
	else
		echo "[`date`] LAC mode" >> /tmp/l2tp_dbg

		# for lac
		procd_open_instance
		procd_set_param command $BIN -D -l -p "$PID_F"
		procd_set_param respawn
		procd_close_instance
	fi
}

stop_service() {
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}

reload_service(){
        local enabled
        config_load xl2tpd
        config_get enabled xl2tpd enabled
        [ -n "$enabled" ] || enabled=0

        rc_procd stop_service "$@"
        rc_procd start_service "$@"	# LNS or LAC ether one
}

service_triggers () {
        procd_add_reload_trigger "xl2tpd"

        procd_open_validate
        validate_xl2tpd_section
        validate_login_section
        procd_close_validate
}
