#ifndef __MIB_H__
#define __MIB_H__

#define MIB_DATA_TYPE "/etc/config/.mib_type"

//9617C
#if defined(CONFIG_ARCH_REALTEK_TAURUS)
#define PE0_DEFAULT_FUNCTION_VALUE "-1"
#define PE2_DEFAULT_FUNCTION_VALUE "-1"
#if defined(CONFIG_RTK_FC_WIFI_AMSDU_OFFLOAD_BY_PE)
#define PE1_DEFAULT_FUNCTION_VALUE "0"
#elif defined(CONFIG_RTK_FC_HTTP_OFFLOAD_BY_PE) || defined(CONFIG_RTK_FC_CRYPTO_OFFLOAD_BY_PE)
#define PE1_DEFAULT_FUNCTION_VALUE "1"
#else
#define PE1_DEFAULT_FUNCTION_VALUE "-1"
#endif
// end 9617C

//9607F
#elif defined(CONFIG_ARCH_REALTEK_9607F)
#if defined(CONFIG_RTK_FC_WIFI_DRIVER_OFFLOAD_BY_PE)
#define PE0_DEFAULT_FUNCTION_VALUE "3"
#else
#define PE0_DEFAULT_FUNCTION_VALUE "-1"
#endif
#if defined(CONFIG_RTK_FC_HTTP_OFFLOAD_BY_PE) || defined(CONFIG_RTK_FC_CRYPTO_OFFLOAD_BY_PE)
#define PE1_DEFAULT_FUNCTION_VALUE "1"
#elif defined(CONFIG_RTK_FC_WIFI_DRIVER_OFFLOAD_BY_PE)
#define PE1_DEFAULT_FUNCTION_VALUE "3"
#else
#define PE1_DEFAULT_FUNCTION_VALUE "-1"
#endif
#if defined(CONFIG_RTK_FC_WIFI_AMSDU_OFFLOAD_BY_PE)
#define PE2_DEFAULT_FUNCTION_VALUE "0"
#else
#define PE2_DEFAULT_FUNCTION_VALUE "-1"
#endif
// end 9607F

// the other platform
#else
#define PE0_DEFAULT_FUNCTION_VALUE "-1"
#define PE1_DEFAULT_FUNCTION_VALUE "-1"
#define PE2_DEFAULT_FUNCTION_VALUE "-1"
#endif

typedef enum MIB_DATABASE_e {
	MIB_DATABASE_XML = 1,
	MIB_DATABASE_UCI = 2
}MIB_DATABASE;

typedef enum MIB_TYPE_e {
	MIB_TYPE_NONE = 0,
	MIB_TYPE_INT,
	MIB_TYPE_INT8,
	MIB_TYPE_DOUBLE,
	MIB_TYPE_BOOLEAN,
	MIB_TYPE_STR,
	MIB_TYPE_BINSTR,
	MIB_TYPE_MAX
} MIB_TYPE;

typedef enum MIB_DATA_e {
	MIB_DATA_UCI = 0,
	MIB_DATA_CS,
	MIB_DATA_HS,
	MIB_DATA_ALL
} MIB_DATA;

typedef enum MIB_ID_e {
	// HS
	MIB_ELAN_MAC_ADDR,
	MIB_WAN_PHY_PORT,
	MIB_PORT_REMAPPING,
	MIB_DEVICE_TYPE,
	MIB_PON_MODE,
	MIB_PON_SUB_MODE,
	MIB_PON_SPEED,
	MIB_GPON_SN,
	MIB_PON_LED_SPEC,
	MIB_HW_XCAP_AX,
	MIB_HW_XCAP_WLAN0_AX,
	MIB_HW_XCAP_WLAN1_AX,
	MIB_HW_XCAP_WLAN2_AX,
	MIB_HW_2G_CCK_TSSI_A,
	MIB_HW_2G_CCK_TSSI_B,
	MIB_HW_2G_CCK_TSSI_C,
	MIB_HW_2G_CCK_TSSI_D,
	MIB_HW_2G_CCK_TSSI_GAIN_DIFF_A,
	MIB_HW_2G_CCK_TSSI_GAIN_DIFF_B,
	MIB_HW_2G_CCK_TSSI_GAIN_DIFF_C,
	MIB_HW_2G_CCK_TSSI_GAIN_DIFF_D,
	MIB_HW_2G_CCK_TSSI_CW_DIFF_A,
	MIB_HW_2G_CCK_TSSI_CW_DIFF_B,
	MIB_HW_2G_CCK_TSSI_CW_DIFF_C,
	MIB_HW_2G_CCK_TSSI_CW_DIFF_D,
	MIB_HW_2G_BW40_1S_TSSI_A,
	MIB_HW_2G_BW40_1S_TSSI_B,
	MIB_HW_2G_BW40_1S_TSSI_C,
	MIB_HW_2G_BW40_1S_TSSI_D,
	MIB_HW_2G_TSSI_GAIN_DIFF_A,
	MIB_HW_2G_TSSI_GAIN_DIFF_B,
	MIB_HW_2G_TSSI_GAIN_DIFF_C,
	MIB_HW_2G_TSSI_GAIN_DIFF_D,
	MIB_HW_2G_TSSI_CW_DIFF_A,
	MIB_HW_2G_TSSI_CW_DIFF_B,
	MIB_HW_2G_TSSI_CW_DIFF_C,
	MIB_HW_2G_TSSI_CW_DIFF_D,
	MIB_HW_5G_BW40_1S_TSSI_A,
	MIB_HW_5G_BW40_1S_TSSI_B,
	MIB_HW_5G_BW40_1S_TSSI_C,
	MIB_HW_5G_BW40_1S_TSSI_D,
	MIB_HW_5G_TSSI_GAIN_DIFF_A,
	MIB_HW_5G_TSSI_GAIN_DIFF_B,
	MIB_HW_5G_TSSI_GAIN_DIFF_C,
	MIB_HW_5G_TSSI_GAIN_DIFF_D,
	MIB_HW_5G_TSSI_CW_DIFF_A,
	MIB_HW_5G_TSSI_CW_DIFF_B,
	MIB_HW_5G_TSSI_CW_DIFF_C,
	MIB_HW_5G_TSSI_CW_DIFF_D,
	MIB_HW_THERMAL_A,
	MIB_HW_THERMAL_B,
	MIB_HW_THERMAL_C,
	MIB_HW_THERMAL_D,
	MIB_HW_THERMAL_A_WLAN0,
	MIB_HW_THERMAL_B_WLAN0,
	MIB_HW_THERMAL_C_WLAN0,
	MIB_HW_THERMAL_D_WLAN0,
	MIB_HW_THERMAL_A_WLAN1,
	MIB_HW_THERMAL_B_WLAN1,
	MIB_HW_THERMAL_C_WLAN1,
	MIB_HW_THERMAL_D_WLAN1,
	MIB_HW_THERMAL_A_WLAN2,
	MIB_HW_THERMAL_B_WLAN2,
	MIB_HW_THERMAL_C_WLAN2,
	MIB_HW_THERMAL_D_WLAN2,
	MIB_HW_RX_GAINGAP_2G_OFDM_AB,
	MIB_HW_RX_GAINGAP_2G_OFDM_CD,
	MIB_HW_RX_GAINGAP_2G_CCK_AB,
	MIB_HW_RX_GAINGAP_2G_CCK_CD,
	MIB_HW_RX_GAINGAP_5GL_AB,
	MIB_HW_RX_GAINGAP_5GL_CD,
	MIB_HW_RX_GAINGAP_5GM_AB,
	MIB_HW_RX_GAINGAP_5GM_CD,
	MIB_HW_RX_GAINGAP_5GH_AB,
	MIB_HW_RX_GAINGAP_5GH_CD,
	MIB_HW_CHANNEL_PLAN_5G,
	MIB_HW_IQK_LCK_MODE,
    MIB_HW_PA_TYPE_2G,
    MIB_HW_PA_TYPE_5G,
    MIB_HW_LNA_TYPE_GAIN_2G,
    MIB_HW_LNA_TYPE_GAIN_5G,
    MIB_HW_BOARD_OPTIONS,
    MIB_HW_EEPROM_VERSION,
    MIB_HW_CUSTOMER_ID,
    MIB_HW_TX_BB_SWING_2G,
    MIB_HW_TX_BB_SWING_5G,
    MIB_HW_TXPWR_CALIBRATE_RATE,
    MIB_HW_TXPWR_TRACK_MODE,
    MIB_HW_TX_RX_PATH,
    MIB_HW_RFE_TYPE,
    MIB_HW_RFE_TYPE_WLAN0,
    MIB_HW_RFE_TYPE_WLAN1,
    MIB_HW_COUNTRY_CODE,
    MIB_HW_CUSTOM_PARA_PATH,
	MIB_HW_SERIAL_NUMBER,
	MIB_HW_DEVINFO_SPECVER,
	// CS
	MIB_PON_REG_MODE,
	MIB_LOID,
	MIB_LOID_PASSWD,
	MIB_NIC_MIN_LIMIT_PAGES,
	// UCI
	MIB_EPON_CUSTOMER_FLAG,
	MIB_TR142_CUSTOMER_FLAG,
	MIB_TR142_LOG_CFG,
	MIB_BOSA_CUSTOMER_CONFIG_MODE,
	MIB_BOSA_VENDOR_NAME,
	MIB_BOSA_PART_NUMBER,
	MIB_OMCI_DBGLVL,
	MIB_OMCI_LOGFILE,
	MIB_OMCI_PORT_TYPE,
	MIB_DUAL_MGMT_MODE,
	MIB_OMCI_CUSTOM_BDP,
	MIB_OMCI_CUSTOM_RDP,
	MIB_OMCI_CUSTOM_MCAST,
	MIB_OMCI_CUSTOM_ME,
	MIB_OMCI_VENDOR_PRODUCT_CODE,
	MIB_GPON_PLOAM_PASSWD,
	MIB_NIC_SMP_DISPATCH_TX,
	MIB_NIC_SMP_DISPATCH_RX,
	MIB_WLAN_SMP_DISPATCH_RX,
	MIB_WLAN_SMP_DISPATCH_TX,
	MIB_WLAN1_SMP_DISPATCH_RX,
	MIB_WLAN1_SMP_DISPATCH_TX,
	MIB_WLAN2_SMP_DISPATCH_RX,
	MIB_WLAN2_SMP_DISPATCH_TX,
	MIB_PE0_DEFAULT_FUNCTION,
	MIB_PE1_DEFAULT_FUNCTION,
	MIB_PE2_DEFAULT_FUNCTION,
	// 
	MIB_MAX
} MIB_ID;

typedef struct MIB_ENTRY_s {
	MIB_ID id;
	const char *name; //mib name 
	MIB_TYPE type; 
	MIB_DATA data;
	const char *def_val;
} MIB_ENTRY;

MIB_ENTRY* mib_lookup_entry(const char *name);
MIB_ENTRY* mib_lookup_entry2(int mibid);
int mib_init(void);
int mib_deinit(void);
int mib_commit(void);
int mib_config_dump(int dump);
int mib_dump_all(const char *type);
int _mib_set_s(const char *name, MIB_ENTRY *e, const char *val, int size, char trans);
int mib_get_s(const char *name, char *val, int size);
int mib_set_s(const char *name, const char *val, int size);
int mib_get_s2(int mibid, char *val, int size);
int mib_set_s2(int mibid, const char *val, int size);
int mib_chain_get(const char *name, int index, char *val, int size);
int mib_chain_update(const char *name, int index, const char *val, int size);
int mib_default(int type);
int mib_get_type(char *type, int size);
int mib_set_type(const char *type);
#endif
