#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "mib.h"

#define __MIB_ENTRY(i, n, t, d, v)  [i] = {.id = i, .name = n, .type = t, .data = d, .def_val = v}
MIB_ENTRY mib_tree[] = {
	// HS MIB
	__MIB_ENTRY( MIB_ELAN_MAC_ADDR,             "ELAN_MAC_ADDR",            MIB_TYPE_STR,    MIB_DATA_HS,  "00E04C867001" ),
	__MIB_ENTRY( MIB_WAN_PHY_PORT,              "WAN_PHY_PORT",             MIB_TYPE_STR,    MIB_DATA_HS,  "7" ),
	__MIB_ENTRY( MIB_PORT_REMAPPING,            "PORT_REMAPPING",           MIB_TYPE_STR,    MIB_DATA_HS,  "00,01,02,03,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_PON_MODE,                  "PON_MODE",                 MIB_TYPE_STR,    MIB_DATA_HS,  "1" ),
	__MIB_ENTRY( MIB_PON_SUB_MODE,              "PON_SUB_MODE",             MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_PON_SPEED,                 "PON_SPEED",                MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_GPON_SN,                   "GPON_SN",                  MIB_TYPE_STR,    MIB_DATA_HS,  "RTKG11111111" ),
	__MIB_ENTRY( MIB_PON_LED_SPEC,              "PON_LED_SPEC",             MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_XCAP_AX,                "HW_XCAP_AX",               MIB_TYPE_STR,    MIB_DATA_HS,  "63" ),
	__MIB_ENTRY( MIB_HW_XCAP_WLAN0_AX,          "HW_XCAP_WLAN0_AX",         MIB_TYPE_STR,    MIB_DATA_HS,  "63" ),
	__MIB_ENTRY( MIB_HW_XCAP_WLAN1_AX,          "HW_XCAP_WLAN1_AX",         MIB_TYPE_STR,    MIB_DATA_HS,  "63" ),
	__MIB_ENTRY( MIB_HW_XCAP_WLAN2_AX,          "HW_XCAP_WLAN2_AX",         MIB_TYPE_STR,    MIB_DATA_HS,  "63" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_A,          "HW_2G_CCK_TSSI_A",         MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_B,          "HW_2G_CCK_TSSI_B",         MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_C,          "HW_2G_CCK_TSSI_C",         MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_D,          "HW_2G_CCK_TSSI_D",         MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_GAIN_DIFF_A,"HW_2G_TSSI_GAIN_DIFF_A",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_GAIN_DIFF_B,"HW_2G_TSSI_GAIN_DIFF_B",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_GAIN_DIFF_C,"HW_2G_TSSI_GAIN_DIFF_C",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_GAIN_DIFF_D,"HW_2G_TSSI_GAIN_DIFF_D",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_CW_DIFF_A,  "HW_2G_CCK_TSSI_CW_DIFF_A", MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_CW_DIFF_B,  "HW_2G_CCK_TSSI_CW_DIFF_B", MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_CW_DIFF_C,  "HW_2G_CCK_TSSI_CW_DIFF_C", MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_CCK_TSSI_CW_DIFF_D,  "HW_2G_CCK_TSSI_CW_DIFF_D", MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_BW40_1S_TSSI_A,      "HW_2G_BW40_1S_TSSI_A",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_BW40_1S_TSSI_B,      "HW_2G_BW40_1S_TSSI_B",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_BW40_1S_TSSI_C,      "HW_2G_BW40_1S_TSSI_C",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_BW40_1S_TSSI_D,      "HW_2G_BW40_1S_TSSI_D",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_GAIN_DIFF_A,    "HW_2G_TSSI_GAIN_DIFF_A",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_GAIN_DIFF_B,    "HW_2G_TSSI_GAIN_DIFF_B",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_GAIN_DIFF_C,    "HW_2G_TSSI_GAIN_DIFF_C",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_GAIN_DIFF_D,    "HW_2G_TSSI_GAIN_DIFF_D",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_CW_DIFF_A,      "HW_2G_TSSI_CW_DIFF_A",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_CW_DIFF_B,      "HW_2G_TSSI_CW_DIFF_B",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_CW_DIFF_C,      "HW_2G_TSSI_CW_DIFF_C",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_2G_TSSI_CW_DIFF_D,      "HW_2G_TSSI_CW_DIFF_D",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_BW40_1S_TSSI_A,      "HW_5G_BW40_1S_TSSI_A",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_BW40_1S_TSSI_B,      "HW_5G_BW40_1S_TSSI_B",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_BW40_1S_TSSI_C,      "HW_5G_BW40_1S_TSSI_C",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_BW40_1S_TSSI_D,      "HW_5G_BW40_1S_TSSI_D",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_GAIN_DIFF_A,    "HW_5G_TSSI_GAIN_DIFF_A",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_GAIN_DIFF_B,    "HW_5G_TSSI_GAIN_DIFF_B",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_GAIN_DIFF_C,    "HW_5G_TSSI_GAIN_DIFF_C",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_GAIN_DIFF_D,    "HW_5G_TSSI_GAIN_DIFF_D",   MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_CW_DIFF_A,      "HW_5G_TSSI_CW_DIFF_A",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_CW_DIFF_B,      "HW_5G_TSSI_CW_DIFF_B",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_CW_DIFF_C,      "HW_5G_TSSI_CW_DIFF_C",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_5G_TSSI_CW_DIFF_D,      "HW_5G_TSSI_CW_DIFF_D",     MIB_TYPE_BINSTR, MIB_DATA_HS,  "00,00,00,00,00,00,00,00,00,00,00,00,00,00" ),
	__MIB_ENTRY( MIB_HW_THERMAL_A,              "HW_THERMAL_A",             MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_B,              "HW_THERMAL_B",             MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_C,              "HW_THERMAL_C",             MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_D,              "HW_THERMAL_D",             MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_A_WLAN0,        "HW_THERMAL_A_WLAN0",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_B_WLAN0,        "HW_THERMAL_B_WLAN0",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_C_WLAN0,        "HW_THERMAL_C_WLAN0",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_D_WLAN0,        "HW_THERMAL_D_WLAN0",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_A_WLAN1,        "HW_THERMAL_A_WLAN1",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_B_WLAN1,        "HW_THERMAL_B_WLAN1",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_C_WLAN1,        "HW_THERMAL_C_WLAN1",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_D_WLAN1,        "HW_THERMAL_D_WLAN1",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_A_WLAN2,        "HW_THERMAL_A_WLAN2",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_B_WLAN2,        "HW_THERMAL_B_WLAN2",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_C_WLAN2,        "HW_THERMAL_C_WLAN2",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_THERMAL_D_WLAN2,        "HW_THERMAL_D_WLAN2",       MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_2G_OFDM_AB,  "HW_RX_GAINGAP_2G_OFDM_AB", MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_2G_OFDM_CD,  "HW_RX_GAINGAP_2G_OFDM_CD", MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_2G_CCK_AB,   "HW_RX_GAINGAP_2G_CCK_AB",  MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_2G_CCK_CD,   "HW_RX_GAINGAP_2G_CCK_CD",  MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GL_AB,      "HW_RX_GAINGAP_5GL_AB",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GL_CD,      "HW_RX_GAINGAP_5GL_CD",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GM_AB,      "HW_RX_GAINGAP_5GM_AB",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GM_CD,      "HW_RX_GAINGAP_5GM_CD",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GH_AB,      "HW_RX_GAINGAP_5GH_AB",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_RX_GAINGAP_5GH_CD,      "HW_RX_GAINGAP_5GH_CD",     MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	__MIB_ENTRY( MIB_HW_CHANNEL_PLAN_5G,        "HW_CHANNEL_PLAN",          MIB_TYPE_STR,    MIB_DATA_HS,  "127" ),
	__MIB_ENTRY( MIB_HW_IQK_LCK_MODE,           "HW_IQK_LCK_MODE",          MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_PA_TYPE_2G,             "HW_PA_TYPE_2G",            MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_PA_TYPE_5G,             "HW_PA_TYPE_5G",            MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_LNA_TYPE_GAIN_2G,       "HW_LNA_TYPE_GAIN_2G",      MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_LNA_TYPE_GAIN_5G,       "HW_LNA_TYPE_GAIN_5G",      MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_BOARD_OPTIONS,          "HW_BOARD_OPTIONS",         MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_EEPROM_VERSION,         "HW_EEPROM_VERSION",        MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_CUSTOMER_ID,            "HW_CUSTOMER_ID",           MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_TX_BB_SWING_2G,         "HW_TX_BB_SWING_2G",        MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_TX_BB_SWING_5G,         "HW_TX_BB_SWING_5G",        MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_TXPWR_CALIBRATE_RATE,   "HW_TXPWR_CALIBRATE_RATE",  MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_TXPWR_TRACK_MODE,       "HW_TXPWR_TRACK_MODE",      MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_TX_RX_PATH,             "HW_TX_RX_PATH",            MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
    __MIB_ENTRY( MIB_HW_RFE_TYPE,               "HW_RFE_TYPE",              MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
    __MIB_ENTRY( MIB_HW_RFE_TYPE_WLAN0,         "HW_RFE_TYPE_WLAN0",        MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
    __MIB_ENTRY( MIB_HW_RFE_TYPE_WLAN1,         "HW_RFE_TYPE_WLAN1",        MIB_TYPE_STR,    MIB_DATA_HS,  "255" ),
    __MIB_ENTRY( MIB_HW_COUNTRY_CODE,           "HW_COUNTRY_CODE",          MIB_TYPE_STR,    MIB_DATA_HS,  "65535" ),
    __MIB_ENTRY( MIB_HW_CUSTOM_PARA_PATH,       "HW_CUSTOM_PARA_PATH",      MIB_TYPE_STR,    MIB_DATA_HS,  "/etc/conf/" ),
	__MIB_ENTRY( MIB_HW_SERIAL_NUMBER,          "HW_SERIAL_NO",             MIB_TYPE_STR,    MIB_DATA_HS,  "000000000002" ),
	__MIB_ENTRY( MIB_HW_DEVINFO_SPECVER,        "RTK_DEVINFO_SPECVER",      MIB_TYPE_STR,    MIB_DATA_HS,  "0" ),
	// CS MIB  
	// UCI MIB 
	__MIB_ENTRY( MIB_PON_REG_MODE,              "PON_REG_MODE",             MIB_TYPE_STR,    MIB_DATA_UCI,  "0" ),
	__MIB_ENTRY( MIB_LOID,                      "LOID",                     MIB_TYPE_STR,    MIB_DATA_UCI,  "" ),
	__MIB_ENTRY( MIB_LOID_PASSWD,               "LOID_PASSWD",              MIB_TYPE_STR,    MIB_DATA_UCI,  "" ),
	__MIB_ENTRY( MIB_DEVICE_TYPE,               "DEVICE_TYPE",              MIB_TYPE_STR,    MIB_DATA_UCI, "1" ),
	__MIB_ENTRY( MIB_EPON_CUSTOMER_FLAG,        "EPON_CUSTOMER_FLAG",       MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_TR142_CUSTOMER_FLAG,       "TR142_CUSTOMER_FLAG",      MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_TR142_LOG_CFG,             "TR142_LOG_CFG",            MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_BOSA_CUSTOMER_CONFIG_MODE, "BOSA_CUSTOMER_CONFIG_MODE",MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_BOSA_VENDOR_NAME,          "BOSA_VENDOR_NAME",         MIB_TYPE_STR,    MIB_DATA_UCI, "Realtek" ),
	__MIB_ENTRY( MIB_BOSA_PART_NUMBER,          "BOSA_PART_NUMBER",         MIB_TYPE_STR,    MIB_DATA_UCI, "" ),
	__MIB_ENTRY( MIB_OMCI_DBGLVL,               "OMCI_DBGLVL",              MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_OMCI_LOGFILE,              "OMCI_LOGFILE",             MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_OMCI_PORT_TYPE,            "OMCI_PORT_TYPE",           MIB_TYPE_STR,    MIB_DATA_UCI, "1" ),
	__MIB_ENTRY( MIB_DUAL_MGMT_MODE,            "DUAL_MGMT_MODE",           MIB_TYPE_STR,    MIB_DATA_UCI, "1" ),
	__MIB_ENTRY( MIB_OMCI_CUSTOM_BDP,           "OMCI_CUSTOM_BDP",          MIB_TYPE_STR,    MIB_DATA_UCI, "128" ),
	__MIB_ENTRY( MIB_OMCI_CUSTOM_RDP,           "OMCI_CUSTOM_RDP",          MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_OMCI_CUSTOM_MCAST,         "OMCI_CUSTOM_MCAST",        MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_OMCI_CUSTOM_ME,            "OMCI_CUSTOM_ME",           MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_OMCI_VENDOR_PRODUCT_CODE,  "OMCI_VENDOR_PRODUCT_CODE", MIB_TYPE_STR,    MIB_DATA_UCI, "0" ),
	__MIB_ENTRY( MIB_GPON_PLOAM_PASSWD,         "GPON_PLOAM_PASSWD",        MIB_TYPE_STR,    MIB_DATA_UCI, "" ),
	__MIB_ENTRY( MIB_NIC_SMP_DISPATCH_TX,       "NIC_SMP_DISPATCH_TX",      MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_NIC_SMP_DISPATCH_RX,       "NIC_SMP_DISPATCH_RX",      MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN_SMP_DISPATCH_RX,      "WLAN_SMP_DISPATCH_RX",     MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN_SMP_DISPATCH_TX,      "WLAN_SMP_DISPATCH_TX",     MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN1_SMP_DISPATCH_RX,     "WLAN1_SMP_DISPATCH_RX",    MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN1_SMP_DISPATCH_TX,     "WLAN1_SMP_DISPATCH_TX",    MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN2_SMP_DISPATCH_RX,     "WLAN2_SMP_DISPATCH_RX",    MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_WLAN2_SMP_DISPATCH_TX,     "WLAN2_SMP_DISPATCH_TX",    MIB_TYPE_STR,    MIB_DATA_UCI, "-1" ),
	__MIB_ENTRY( MIB_NIC_MIN_LIMIT_PAGES,       "NIC_MIN_LIMIT_PAGES",      MIB_TYPE_INT,    MIB_DATA_UCI, "20480" ),
	__MIB_ENTRY( MIB_PE0_DEFAULT_FUNCTION,      "PE0_DEFAULT_FUNCTION",     MIB_TYPE_INT,    MIB_DATA_UCI, PE0_DEFAULT_FUNCTION_VALUE ),
	__MIB_ENTRY( MIB_PE1_DEFAULT_FUNCTION,      "PE1_DEFAULT_FUNCTION",     MIB_TYPE_INT,    MIB_DATA_UCI, PE1_DEFAULT_FUNCTION_VALUE ),
	__MIB_ENTRY( MIB_PE2_DEFAULT_FUNCTION,      "PE2_DEFAULT_FUNCTION",     MIB_TYPE_INT,    MIB_DATA_UCI, PE2_DEFAULT_FUNCTION_VALUE ),
	__MIB_ENTRY( MIB_MAX,                       NULL,                       MIB_TYPE_STR,    MIB_DATA_UCI, NULL )                    
};

MIB_ENTRY* mib_lookup_entry(const char *name) {
	int i;
	MIB_ENTRY *e = NULL;
	for(i=0;i<MIB_MAX;i++) {
		if(mib_tree[i].name == NULL)
			continue;
		if(!strcmp(mib_tree[i].name, name)) {
			e = &mib_tree[i];
			break;
		}
	}
	if(e == NULL)
		e = &mib_tree[MIB_MAX];
	return e;
}

MIB_ENTRY* mib_lookup_entry2(int mibid) {
	int i;
	MIB_ENTRY *e = NULL;
	if(mibid < MIB_MAX) e = &mib_tree[mibid];
	if(e == NULL)
		e = &mib_tree[MIB_MAX];
	return e;
}
