#ifndef __RTK_INTERFACE_H__
#define __RTK_INTERFACE_H__

#define _DNUM(x) _DNUM_ ## x
#define _DNUM_0 1
#define _DNUM_1 2
#define _DNUM_2 3
#define _DNUM_3 4
#define _DNUM_4 5
#define _DNUM_5 6
#define _DNUM_6 7
#define _DNUM_7 8
#define _DNUM_8 9
#define _DNUM_9 10
#define _DNUM_10 11
#define _DNUM_11 12
#define _DNUM_12 13
#define _DNUM_13 14
#define _DNUM_14 15
#define _DNUM_15 16
#define _DNUM_16 17
#define _DNUM_17 18
#define _DNUM_18 19
#define _DNUM_19 20

#define _DINC_0(x) x
#define _DINC_1(x) _DNUM(x)
#define _DINC_2(x) _DINC_1(_DNUM(x))
#define _DINC_3(x) _DINC_2(_DNUM(x))
#define _DINC_4(x) _DINC_3(_DNUM(x))
#define _DINC_5(x) _DINC_4(_DNUM(x))
#define _DINC_6(x) _DINC_5(_DNUM(x))
#define _DINC_7(x) _DINC_6(_DNUM(x))
#define _DINC_8(x) _DINC_7(_DNUM(x))
#define _DINC_9(x) _DINC_8(_DNUM(x))

#ifndef CONFIG_RTL_ALIASNAME
#define ALIASNAME_VC   "vc"
#define ALIASNAME_BR   "br"
#define ALIASNAME_NAS  "nas"
#define ALIASNAME_DSL  "dsl"
#define ALIASNAME_ETH  "eth"
#define ALIASNAME_WLAN "wlan"
#define ALIASNAME_PPP  "ppp"
#define ALIASNAME_MWNAS  "nas0_"
#define ALIASNAME_ELAN_PREFIX  "eth0."
#define ALIASNAME_PTM  "ptm"
#define ALIASNAME_MWPTM  "ptm0_"
#define ORIGINATE_NUM 2

#else
#define ALIASNAME_VC   CONFIG_ALIASNAME_VC//"vc"
#define ALIASNAME_BR   CONFIG_ALIASNAME_BR//"br"
#define ALIASNAME_NAS  CONFIG_ALIASNAME_NAS//"nas"
#define ALIASNAME_DSL  CONFIG_ALIASNAME_DSL//"dsl"
#define ALIASNAME_ETH  CONFIG_ALIASNAME_ETH//"eth"
#define ALIASNAME_WLAN  CONFIG_ALIASNAME_WLAN//"wlan"
#define ALIASNAME_PPP  CONFIG_ALIASNAME_PPP//"ppp"
#define ALIASNAME_MWNAS  CONFIG_ALIASNAME_MWNAS//"nas0_"
#define ALIASNAME_ELAN_PREFIX  CONFIG_ALIASNAME_ELAN_PREFIX//"eth0."
#define ALIASNAME_PTM  CONFIG_ALIASNAME_PTM//"ptm"
#define ALIASNAME_MWPTM  CONFIG_ALIASNAME_MWPTM//"ptm0_"
#define ORIGINATE_NUM CONFIG_ORIGINATE_NUM

#endif

#ifdef CONFIG_RTK_MULTI_ETH_NIC_NAME_CUSTOMIZE
#undef ALIASNAME_ETH
#define ALIASNAME_ETH CONFIG_RTK_MULTI_ETH_NIC_NAME
#define ALIASNAME_ETH_START CONFIG_RTK_MULTI_ETH_NIC_NAME_IDX
#else 
#define ALIASNAME_ETH_START 0
#endif

#ifdef CONFIG_RTK_MULTI_LAN_NAME_CUSTOMIZE
#undef ALIASNAME_ELAN_PREFIX
#define ALIASNAME_ELAN_PREFIX CONFIG_RTK_MULTI_LAN_NAME
#define ALIASNAME_ELAN_START CONFIG_RTK_MULTI_LAN_NAME_IDX
#else 
#define ALIASNAME_ELAN_START 2
#endif

#ifdef CONFIG_RTK_MULTI_WAN_NAME_CUSTOMIZE
#undef ALIASNAME_NAS
#define ALIASNAME_NAS CONFIG_RTK_MULTI_WAN_NAME
#define ALIASNAME_NAS_START CONFIG_RTK_MULTI_WAN_NAME_IDX
#else
#define ALIASNAME_NAS_START 0	
#endif

#define RTL_IDX_NUM1(start,num) _DINC_ ##start (num)
#define RTL_IDX_NUM(start,num) RTL_IDX_NUM1(start,num)
#define RTL_DEV_NAME(name,num)	name#num
#define RTL_DEV_NAME_NUM(name,num)	RTL_DEV_NAME(name,num)

#define ALIASNAME_NAS0  RTL_DEV_NAME_NUM(ALIASNAME_NAS, RTL_IDX_NUM(ALIASNAME_NAS_START, 0))//"nas0"
#define ALIASNAME_NAS1  RTL_DEV_NAME_NUM(ALIASNAME_NAS, RTL_IDX_NUM(ALIASNAME_NAS_START, 1))//"nas1"
#define ALIASNAME_NAS2  RTL_DEV_NAME_NUM(ALIASNAME_NAS, RTL_IDX_NUM(ALIASNAME_NAS_START, 2))//"nas2"
#define ALIASNAME_PTM0  RTL_DEV_NAME_NUM(ALIASNAME_PTM,0)//"ptm0"

#if defined(CONFIG_GPON_FEATURE) || defined(CONFIG_EPON_FEATURE)
#ifndef PON_PHY_IF
#define PON_PHY_IF ALIASNAME_NAS0
#endif
#ifndef PON_VEIP_IF
#define PON_VEIP_IF "veip"
#endif
#ifndef PON_PPTP_IF
#define PON_PPTP_IF "pptp"
#endif
#ifndef PON_VEIP_IPHOST_IF
#define PON_VEIP_IPHOST_IF "veip0_"
#endif
#endif

#define ALIASNAME_ETH0  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 0))
#define ALIASNAME_ETH1  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 1))
#define ALIASNAME_ETH2  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 2))
#define ALIASNAME_ETH3  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 3))
#define ALIASNAME_ETH4  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 4))
#define ALIASNAME_ETH5  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 5))
#define ALIASNAME_ETH6  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 6))
#define ALIASNAME_ETH7  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 7))
#define ALIASNAME_ETH8  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 8))
#define ALIASNAME_ETH9  RTL_DEV_NAME_NUM(ALIASNAME_ETH,  RTL_IDX_NUM(ALIASNAME_ETH_START, 9))
#define ALIASNAME_ETH10  RTL_DEV_NAME_NUM(ALIASNAME_ETH, RTL_IDX_NUM(ALIASNAME_ETH_START, 10))

#define ALIASNAME_DSL0  RTL_DEV_NAME_NUM(ALIASNAME_DSL,0)//dsl0
#define ALIASNAME_ELAN0  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 0))
#define ALIASNAME_ELAN1  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 1))
#define ALIASNAME_ELAN2  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 2))
#define ALIASNAME_ELAN3  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 3))
#define ALIASNAME_ELAN4  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 4))
#define ALIASNAME_ELAN5  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 5))
#define ALIASNAME_ELAN6  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 6))
#define ALIASNAME_ELAN7  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 7))
#define ALIASNAME_ELAN8  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 8))
#define ALIASNAME_ELAN9  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 9))
#define ALIASNAME_ELAN10  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX, RTL_IDX_NUM(ALIASNAME_ELAN_START, 10))

#define RTL_VDEV_NAME_NUM(name,num)	name"."#num
#define ALIASNAME_VELAN0 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN0, 0)
#define ALIASNAME_VELAN1 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN1, 0)
#define ALIASNAME_VELAN2 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN2, 0)
#define ALIASNAME_VELAN3 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN3, 0)
#define ALIASNAME_VELAN4 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN4, 0)
#define ALIASNAME_VELAN5 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN5, 0)
#define ALIASNAME_VELAN6 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN6, 0)
#define ALIASNAME_VELAN7 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN7, 0)
#define ALIASNAME_VELAN8 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN8, 0)
#define ALIASNAME_VELAN9 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN9, 0)
#define ALIASNAME_VELAN10 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN10, 0)

#ifdef CONFIG_USER_SUPPORT_EXTERNAL_SWITCH
#define ALIASNAME_EXTELAN_PREFIX  "ext0."
#define ALIASNAME_EXTELAN_START 2
#define ALIASNAME_EXTELAN0  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 0)
#define ALIASNAME_EXTELAN1  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 1)
#define ALIASNAME_EXTELAN2  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 2)
#define ALIASNAME_EXTELAN3  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 3)
#define ALIASNAME_EXTELAN4  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 4)
#define ALIASNAME_EXTELAN5  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 5)
#define ALIASNAME_EXTELAN6  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 6)
#define ALIASNAME_EXTELAN7  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 7)
#define ALIASNAME_EXTELAN8  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 8)
#define ALIASNAME_EXTELAN9  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,  RTL_IDX_NUM(ALIASNAME_ELAN_START, 9)
#define ALIASNAME_EXTELAN10  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX, RTL_IDX_NUM(ALIASNAME_ELAN_START, 10)
#endif

#define ALIASNAME_BR0   RTL_DEV_NAME_NUM(ALIASNAME_BR,0)//"br0"
#define ALIASNAME_WLAN0  RTL_DEV_NAME_NUM(ALIASNAME_WLAN,0)//"wlan0"

#define ALIASNAME_VAP   "-vap" //must include '-' at fast
#define ALIASNAME_WLAN0_VAP  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0,-vap)//"wlan0-vap"

#define ALIASNAME_WLAN0_VAP0  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,0)//"wlan0-vap0"
#define ALIASNAME_WLAN0_VAP1  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,1)//"wlan0-vap1"
#define ALIASNAME_WLAN0_VAP2  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,2)//"wlan0-vap2"
#define ALIASNAME_WLAN0_VAP3  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,3)//"wlan0-vap3"

#define ALIASNAME_VXD   "-vxd"

#define WANMODE_CONF_STR "WAN Mode"
#define PON_CONF_STR "PON WAN"
#define ETHWAN_CONF_STR "Ethernet WAN"
#define PTMWAN_CONF_STR "PTM WAN"
#ifdef WLAN_WISP
#define WLWAN_CONF_STR "Wireless WAN"
#endif
#ifdef CONFIG_VDSL
#define DSLWAN_CONF_STR "ATM WAN"
#define ADSL_SETTINGS_STR "DSL Settings"
#define ADSL_STR "DSL"
#define ADSL_TONE_STR "DSL Tone"
#define ADSL_SLV_STR "DSL Slave"
#define ADSL_SLV_TONE_STR "DSL Slave Tone"
#else
#define DSLWAN_CONF_STR "DSL WAN"
#define ADSL_SETTINGS_STR "ADSL Settings"
#define ADSL_STR "ADSL"
#define ADSL_TONE_STR "ADSL Tone"
#define ADSL_SLV_STR "ADSL Slave"
#define ADSL_SLV_TONE_STR "ADSL Slave Tone"
#endif /*CONFIG_VDSL*/
#define ATM_SETTINGS_STR "ATM Settings"
#define ATM_LOOPBACK_STR "ATM Loopback"
#define ADSL_CONNECTION_STR "ADSL Connection"
#ifdef CONFIG_DSL_VTUO
#define VTUO_SETTINGS_STR "VTU-O DSL Settings"
#define VTUO_STATUS_STR "VTU-O DSL"
#endif /*CONFIG_DSL_VTUO*/

#ifdef WLAN_8_SSID_SUPPORT
typedef enum MARK
{
	PMAP_ETH0_SW0 = 0,
	PMAP_ETH0_SW1,
	PMAP_ETH0_SW2,
#ifdef CONFIG_RTL_MULTI_PHY_ETH_WAN
	PMAP_ETH0_SW3=CONFIG_LAN_PORT_NUM,
#else
	PMAP_ETH0_SW3,
#endif
	PMAP_WLAN0,
	PMAP_WLAN0_VAP0,
	PMAP_WLAN0_VAP1,
	PMAP_WLAN0_VAP2,
	PMAP_WLAN0_VAP3,
	PMAP_WLAN0_VAP4,
	PMAP_WLAN0_VAP5,
	PMAP_WLAN0_VAP6,
	PMAP_WLAN1,
	PMAP_WLAN1_VAP0,
	PMAP_WLAN1_VAP1,
	PMAP_WLAN1_VAP2,
	PMAP_WLAN1_VAP3,
	PMAP_WLAN1_VAP4,
	PMAP_WLAN1_VAP5,
	PMAP_WLAN1_VAP6,
	PMAP_ITF_END
} PMAP_LAN_T;
#else
typedef enum MARK
{
	PMAP_ETH0_SW0 = 0,
	PMAP_ETH0_SW1,
	PMAP_ETH0_SW2,
#ifdef CONFIG_RTL_MULTI_PHY_ETH_WAN
	PMAP_ETH0_SW3=CONFIG_LAN_PORT_NUM,
#else
	PMAP_ETH0_SW3,
#endif
	PMAP_WLAN0,
	PMAP_WLAN0_VAP0,
	PMAP_WLAN0_VAP1,
	PMAP_WLAN0_VAP2,
	PMAP_WLAN0_VAP3,
	PMAP_WLAN1,
	PMAP_WLAN1_VAP0,
	PMAP_WLAN1_VAP1,
	PMAP_WLAN1_VAP2,
	PMAP_WLAN1_VAP3,
#if defined(CONFIG_RTK_DEV_AP)
	PMAP_WLAN2,
	PMAP_WLAN2_VAP0,
	PMAP_WLAN2_VAP1,
	PMAP_WLAN2_VAP2,
	PMAP_WLAN2_VAP3,
#endif
	PMAP_ITF_END
} PMAP_LAN_T;
#endif

#ifdef WLAN_8_SSID_SUPPORT
#define PMAP_WLAN0_VAP_END PMAP_WLAN0_VAP6
#define PMAP_WLAN1_VAP_END PMAP_WLAN1_VAP6
#else
#define PMAP_WLAN0_VAP_END PMAP_WLAN0_VAP3
#define PMAP_WLAN1_VAP_END PMAP_WLAN1_VAP3
#endif

#ifndef NUM_WLAN_INTERFACE
#define NUM_WLAN_INTERFACE 2
#endif

#endif // __RTK_INTERFACE_H__
