#include <stdio.h>
#include "wifi_mib.h"
#include "mib.h"

static struct WLAN_MIB_s {
	int idx;
	MIB_ID mib_id[HW_WLAN_MIB_MAX+1];
} WLAN_MIB[] = {
	[0] = { 
		.idx = 0, 
		.mib_id = {
			[HW_XCAP_AX] = MIB_HW_XCAP_WLAN0_AX,
			[HW_THERMAL_A] = MIB_HW_THERMAL_A_WLAN0,
			[HW_THERMAL_B] = MIB_HW_THERMAL_B_WLAN0,
			[HW_THERMAL_C] = MIB_HW_THERMAL_C_WLAN0,
			[HW_THERMAL_D] = MIB_HW_THERMAL_D_WLAN0,
			[HW_2G_CCK_TSSI_A] = MIB_HW_2G_CCK_TSSI_A,
			[HW_2G_CCK_TSSI_B] = MIB_HW_2G_CCK_TSSI_B,
			[HW_2G_CCK_TSSI_C] = MIB_HW_2G_CCK_TSSI_C,
			[HW_2G_CCK_TSSI_D] = MIB_HW_2G_CCK_TSSI_D,
			[HW_2G_BW40_1S_TSSI_A] = MIB_HW_2G_BW40_1S_TSSI_A,
			[HW_2G_BW40_1S_TSSI_B] = MIB_HW_2G_BW40_1S_TSSI_B,
			[HW_2G_BW40_1S_TSSI_C] = MIB_HW_2G_BW40_1S_TSSI_C,
			[HW_2G_BW40_1S_TSSI_D] = MIB_HW_2G_BW40_1S_TSSI_D,
			[HW_5G_BW40_1S_TSSI_A] = MIB_HW_5G_BW40_1S_TSSI_A,
			[HW_5G_BW40_1S_TSSI_B] = MIB_HW_5G_BW40_1S_TSSI_B,
			[HW_5G_BW40_1S_TSSI_C] = MIB_HW_5G_BW40_1S_TSSI_C,
			[HW_5G_BW40_1S_TSSI_D] = MIB_HW_5G_BW40_1S_TSSI_D,
			[HW_2G_CCK_TSSI_GAIN_DIFF_A] = MIB_HW_2G_CCK_TSSI_CW_DIFF_A,
			[HW_2G_CCK_TSSI_GAIN_DIFF_B] = MIB_HW_2G_CCK_TSSI_CW_DIFF_B,
			[HW_2G_CCK_TSSI_GAIN_DIFF_C] = MIB_HW_2G_CCK_TSSI_CW_DIFF_C,
			[HW_2G_CCK_TSSI_GAIN_DIFF_D] = MIB_HW_2G_CCK_TSSI_CW_DIFF_D,
			[HW_2G_TSSI_GAIN_DIFF_A] = MIB_HW_2G_TSSI_GAIN_DIFF_A,
			[HW_2G_TSSI_GAIN_DIFF_B] = MIB_HW_2G_TSSI_GAIN_DIFF_B,
			[HW_2G_TSSI_GAIN_DIFF_C] = MIB_HW_2G_TSSI_GAIN_DIFF_C,
			[HW_2G_TSSI_GAIN_DIFF_D] = MIB_HW_2G_TSSI_GAIN_DIFF_D,
			[HW_5G_TSSI_GAIN_DIFF_A] = MIB_HW_5G_TSSI_GAIN_DIFF_A,
			[HW_5G_TSSI_GAIN_DIFF_B] = MIB_HW_5G_TSSI_GAIN_DIFF_B,
			[HW_5G_TSSI_GAIN_DIFF_C] = MIB_HW_5G_TSSI_GAIN_DIFF_C,
			[HW_5G_TSSI_GAIN_DIFF_D] = MIB_HW_5G_TSSI_GAIN_DIFF_D,
			[HW_2G_CCK_TSSI_CW_DIFF_A] = MIB_HW_2G_CCK_TSSI_CW_DIFF_A,
			[HW_2G_CCK_TSSI_CW_DIFF_B] = MIB_HW_2G_CCK_TSSI_CW_DIFF_B,
			[HW_2G_CCK_TSSI_CW_DIFF_C] = MIB_HW_2G_CCK_TSSI_CW_DIFF_C,
			[HW_2G_CCK_TSSI_CW_DIFF_D] = MIB_HW_2G_CCK_TSSI_CW_DIFF_D,
			[HW_2G_TSSI_CW_DIFF_A] = MIB_HW_2G_TSSI_CW_DIFF_A,
			[HW_2G_TSSI_CW_DIFF_B] = MIB_HW_2G_TSSI_CW_DIFF_B,
			[HW_2G_TSSI_CW_DIFF_C] = MIB_HW_2G_TSSI_CW_DIFF_C,
			[HW_2G_TSSI_CW_DIFF_D] = MIB_HW_2G_TSSI_CW_DIFF_D,
			[HW_5G_TSSI_CW_DIFF_A] = MIB_HW_5G_TSSI_CW_DIFF_A,
			[HW_5G_TSSI_CW_DIFF_B] = MIB_HW_5G_TSSI_CW_DIFF_B,
			[HW_5G_TSSI_CW_DIFF_C] = MIB_HW_5G_TSSI_CW_DIFF_C,
			[HW_5G_TSSI_CW_DIFF_D] = MIB_HW_5G_TSSI_CW_DIFF_D,
			[HW_RX_GAINGAP_2G_CCK_AB] = MIB_HW_RX_GAINGAP_2G_CCK_AB,
			[HW_RX_GAINGAP_2G_OFDM_AB] = MIB_HW_RX_GAINGAP_2G_OFDM_AB,
			[HW_RX_GAINGAP_5GL_AB] = MIB_HW_RX_GAINGAP_5GL_AB,
			[HW_RX_GAINGAP_5GM_AB] = MIB_HW_RX_GAINGAP_5GM_AB,
			[HW_RX_GAINGAP_5GH_AB] = MIB_HW_RX_GAINGAP_5GH_AB,
			[HW_CUSTOM_PARA_PATH] = MIB_HW_CUSTOM_PARA_PATH,
			[HW_WLAN_MIB_MAX] = MIB_MAX
		}
	},
	[1] = {
		.idx = 1, 
		.mib_id = {
			[HW_XCAP_AX] = MIB_HW_XCAP_WLAN1_AX,
			[HW_THERMAL_A] = MIB_HW_THERMAL_A_WLAN1,
			[HW_THERMAL_B] = MIB_HW_THERMAL_B_WLAN1,
			[HW_THERMAL_C] = MIB_HW_THERMAL_C_WLAN1,
			[HW_THERMAL_D] = MIB_HW_THERMAL_D_WLAN1,
			[HW_2G_CCK_TSSI_A] = MIB_HW_2G_CCK_TSSI_A,
			[HW_2G_CCK_TSSI_B] = MIB_HW_2G_CCK_TSSI_B,
			[HW_2G_CCK_TSSI_C] = MIB_HW_2G_CCK_TSSI_C,
			[HW_2G_CCK_TSSI_D] = MIB_HW_2G_CCK_TSSI_D,
			[HW_2G_BW40_1S_TSSI_A] = MIB_HW_2G_BW40_1S_TSSI_A,
			[HW_2G_BW40_1S_TSSI_B] = MIB_HW_2G_BW40_1S_TSSI_B,
			[HW_2G_BW40_1S_TSSI_C] = MIB_HW_2G_BW40_1S_TSSI_C,
			[HW_2G_BW40_1S_TSSI_D] = MIB_HW_2G_BW40_1S_TSSI_D,
			[HW_5G_BW40_1S_TSSI_A] = MIB_HW_5G_BW40_1S_TSSI_A,
			[HW_5G_BW40_1S_TSSI_B] = MIB_HW_5G_BW40_1S_TSSI_B,
			[HW_5G_BW40_1S_TSSI_C] = MIB_HW_5G_BW40_1S_TSSI_C,
			[HW_5G_BW40_1S_TSSI_D] = MIB_HW_5G_BW40_1S_TSSI_D,
			[HW_2G_CCK_TSSI_GAIN_DIFF_A] = MIB_HW_2G_CCK_TSSI_CW_DIFF_A,
			[HW_2G_CCK_TSSI_GAIN_DIFF_B] = MIB_HW_2G_CCK_TSSI_CW_DIFF_B,
			[HW_2G_CCK_TSSI_GAIN_DIFF_C] = MIB_HW_2G_CCK_TSSI_CW_DIFF_C,
			[HW_2G_CCK_TSSI_GAIN_DIFF_D] = MIB_HW_2G_CCK_TSSI_CW_DIFF_D,
			[HW_2G_TSSI_GAIN_DIFF_A] = MIB_HW_2G_TSSI_GAIN_DIFF_A,
			[HW_2G_TSSI_GAIN_DIFF_B] = MIB_HW_2G_TSSI_GAIN_DIFF_B,
			[HW_2G_TSSI_GAIN_DIFF_C] = MIB_HW_2G_TSSI_GAIN_DIFF_C,
			[HW_2G_TSSI_GAIN_DIFF_D] = MIB_HW_2G_TSSI_GAIN_DIFF_D,
			[HW_5G_TSSI_GAIN_DIFF_A] = MIB_HW_5G_TSSI_GAIN_DIFF_A,
			[HW_5G_TSSI_GAIN_DIFF_B] = MIB_HW_5G_TSSI_GAIN_DIFF_B,
			[HW_5G_TSSI_GAIN_DIFF_C] = MIB_HW_5G_TSSI_GAIN_DIFF_C,
			[HW_5G_TSSI_GAIN_DIFF_D] = MIB_HW_5G_TSSI_GAIN_DIFF_D,
			[HW_2G_CCK_TSSI_CW_DIFF_A] = MIB_HW_2G_CCK_TSSI_CW_DIFF_A,
			[HW_2G_CCK_TSSI_CW_DIFF_B] = MIB_HW_2G_CCK_TSSI_CW_DIFF_B,
			[HW_2G_CCK_TSSI_CW_DIFF_C] = MIB_HW_2G_CCK_TSSI_CW_DIFF_C,
			[HW_2G_CCK_TSSI_CW_DIFF_D] = MIB_HW_2G_CCK_TSSI_CW_DIFF_D,
			[HW_2G_TSSI_CW_DIFF_A] = MIB_HW_2G_TSSI_CW_DIFF_A,
			[HW_2G_TSSI_CW_DIFF_B] = MIB_HW_2G_TSSI_CW_DIFF_B,
			[HW_2G_TSSI_CW_DIFF_C] = MIB_HW_2G_TSSI_CW_DIFF_C,
			[HW_2G_TSSI_CW_DIFF_D] = MIB_HW_2G_TSSI_CW_DIFF_D,
			[HW_5G_TSSI_CW_DIFF_A] = MIB_HW_5G_TSSI_CW_DIFF_A,
			[HW_5G_TSSI_CW_DIFF_B] = MIB_HW_5G_TSSI_CW_DIFF_B,
			[HW_5G_TSSI_CW_DIFF_C] = MIB_HW_5G_TSSI_CW_DIFF_C,
			[HW_5G_TSSI_CW_DIFF_D] = MIB_HW_5G_TSSI_CW_DIFF_D,
			[HW_RX_GAINGAP_2G_CCK_AB] = MIB_HW_RX_GAINGAP_2G_CCK_AB,
			[HW_RX_GAINGAP_2G_OFDM_AB] = MIB_HW_RX_GAINGAP_2G_OFDM_AB,
			[HW_RX_GAINGAP_5GL_AB] = MIB_HW_RX_GAINGAP_5GL_AB,
			[HW_RX_GAINGAP_5GM_AB] = MIB_HW_RX_GAINGAP_5GM_AB,
			[HW_RX_GAINGAP_5GH_AB] = MIB_HW_RX_GAINGAP_5GH_AB,
			[HW_CUSTOM_PARA_PATH] = MIB_HW_CUSTOM_PARA_PATH,
			[HW_WLAN_MIB_MAX] = MIB_MAX
		}
	}
};

int _W(int id, int idx)
{
	if(idx > (sizeof(WLAN_MIB)/sizeof(struct WLAN_MIB_s)))
		return MIB_MAX;
	if(id >= HW_WLAN_MIB_MAX)
		return MIB_MAX;
	return (int)WLAN_MIB[idx].mib_id[id];
}