#!/bin/sh
PPP_IPPARAM="$6"
. /lib/functions.sh
. /lib/netifd/netifd-proto.sh
PPP_RESOLV="/etc/ppp/resolv.conf"
proto_init_update "$IFNAME" 1 1
proto_set_keep 1
[ -n "$PPP_IPPARAM" ] && {
	rm $PPP_RESOLV"."$PPP_IPPARAM 2>/dev/null
	[ -n "$IPLOCAL" ] && proto_add_ipv4_address "$IPLOCAL" 32 "" "${IPREMOTE:-2.2.2.2}"
	[ -n "$IPREMOTE" ] && proto_add_ipv4_route 0.0.0.0 0 "$IPREMOTE"
	#for Gateway
	[ -n "$IPREMOTE" ] && echo $IPREMOTE > $RTK_MER_GWINFO"."$1
	[ -n "$DNS1" ] && proto_add_dns_server "$DNS1"
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && proto_add_dns_server "$DNS2"
	[ -n "$DNS1" ] && echo $DNS1 >> $PPP_RESOLV"."$PPP_IPPARAM
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && echo $DNS2 >> $PPP_RESOLV"."$PPP_IPPARAM
	#for resolv_backup.conf
	[ -n "$DNS1" ] && echo $DNS1"@"$PPP_IPPARAM > $RTK_DNS_RESOLV_FILE"."$1
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && echo $DNS2"@"$PPP_IPPARAM >> $RTK_DNS_RESOLV_FILE"."$1
}
proto_send_update "$PPP_IPPARAM"

[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
