#!/bin/sh
#

if [ -d /proc/net/rtk_wifi6/wlan1 ]
then
	echo $@ > /proc/net/rtk_wifi6/wlan1/odm/phl_cmd
	cat /proc/net/rtk_wifi6/wlan1/odm/phl_cmd
elif [ -d /proc/net/rtl8852ae/wlan1 ]
then 
	echo $@ > /proc/net/rtl8852ae/wlan1/odm/phl_cmd
	cat /proc/net/rtl8852ae/wlan1/odm/phl_cmd
else
	echo $@ > /proc/wlan1/cmd
fi
