#!/bin/sh
#

if [ $# -lt 2 ]; then echo "Usage: $0 <path> <offset>";  exit 1 ; fi

if [ -d /proc/net/rtk_wifi6/wlan0 ] || [ -d /proc/net/rtl8852ae/wlan0 ]
then 
	iwpriv wlan0 rfr $1 $2
else
	iwpriv wlan0 read_rf $1,$2
fi
