#!/bin/sh
#

if [ $# -lt 2 ]; then echo "Usage: $0 <path> <offset>";  exit 1 ; fi

if [ -d /proc/net/rtk_wifi6/wlan1 ] || [ -d /proc/net/rtl8852ae/wlan1 ]
then 
	iwpriv wlan1 rfr $1 $2
else
	iwpriv wlan1 read_rf $1,$2
fi
