#!/bin/sh
#

if [ $# -lt 2 ]; then echo "Usage: $0 <offset> <data>";  exit 1 ; fi

if [ -d /proc/net/rtk_wifi6/wlan1 ]
then
	echo 0x$1 $2 1 > /proc/net/rtk_wifi6/wlan1/write_reg
	echo 0x$1 1 > /proc/net/rtk_wifi6/wlan1/read_reg
	cat /proc/net/rtk_wifi6/wlan1/read_reg
elif [ -d /proc/net/rtl8852ae/wlan1 ]
then 
	echo 0x$1 $2 1 > /proc/net/rtl8852ae/wlan1/write_reg
	echo 0x$1 1 > /proc/net/rtl8852ae/wlan1/read_reg
	cat /proc/net/rtl8852ae/wlan1/read_reg
else
	iwpriv wlan1 write_reg b,$1,$2
fi
