#!/bin/sh
#

if [ $# -lt 3 ]; then echo "Usage: $0 <path> <offset> <data>";  exit 1 ; fi

if [ -d /proc/net/rtk_wifi6/wlan1 ] || [ -d /proc/net/rtl8852ae/wlan1 ]
then 
	iwpriv wlan1 rfw $1 $2 $3
else
	iwpriv wlan1 write_rf $1,$2,$3
fi
