#!/bin/sh
#

if [ $# -lt 2 ]; then echo "Usage: $0 <offset> <data>";  exit 1 ; fi

if [ -d /proc/net/rtk_wifi6/wlan0 ]
then
	echo 0x$1 $2 2 > /proc/net/rtk_wifi6/wlan0/write_reg
	echo 0x$1 2 > /proc/net/rtk_wifi6/wlan0/read_reg
	cat /proc/net/rtk_wifi6/wlan0/read_reg
elif [ -d /proc/net/rtl8852ae/wlan0 ]
then 
	echo 0x$1 $2 2 > /proc/net/rtl8852ae/wlan0/write_reg
	echo 0x$1 2 > /proc/net/rtl8852ae/wlan0/read_reg
	cat /proc/net/rtl8852ae/wlan0/read_reg
else
	iwpriv wlan0 write_reg w,$1,$2
fi
