#!/bin/sh
script_file="/root/testing-script/app_ft-script.sh"

if [ -x ${script_file} ]; then
	cd /root/testing-script
	./app_ft-script.sh
else	
	cd /root
	tar -zxvf /usr/local/testing-script.tgz
	sync
	sync
	cd /root/testing-script
	chmod +x *.sh
	./app_ft-script.sh
fi
cd /

