include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-rtk-igmpproxy
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for igmpproxy
LUCI_DEPENDS:=+igmpproxy
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
