#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG="/usr/sbin/bulkdatad"

start_service() {
	local enable=$(uci -q get bulkdata.bulkdata.enable)

	[ "$enable" != "1" ] && {
		return 0
	}

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn "3" "7" "0"
	procd_close_instance
}

boot() {
	start
}

reload_service() {
	stop
	start 
}

service_triggers()
{
	procd_add_reload_trigger bulkdata
}
