/*
 * Copyright (C) 2020 Realtek Semiconductor Corp. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>          // errno
#include <sys/ioctl.h>      // ioctl()
#include <sys/socket.h>     // socket()
#include <linux/wireless.h> // struct iwreq
#include <unistd.h>         // close()

#include <ctype.h>
#include <stdarg.h>
#include <sys/wait.h>

#include "config_file_handler.h"
//#include "mib.h"
//#include "sysconfig.h"
#ifdef WLAN_SCHEDULE_SUPPORT
//#include "subr_wlan.h"
#endif
//#include "subr_multiap.h"

#include "ini.h"
#include "easymesh_datamodel.h"
#include "map_initialization.h"

/* ******************************** */
/* Sync from user/sysconf/sysconf.c */
/* ******************************** */

/* ENVP parameter & event name */
#define ENVP_MAP_RELOAD					"reason=multi_ap_reload"				/* multi-ap reload setting. */
#define ENVP_MAP_CONFIGURE				"reason=multi_ap_configure"				/* multi-ap configure setting. */
#define ENVP_MAP_SET_CONFIGURED_BAND	"reason=multi_ap_set_configured_band"	/* multi-ap configured band. */
#define ENVP_MAP_SET_BAND				"reason=multi_ap_set_band"				/* multi-ap band setting. */
#define ENVP_MAP_WLAN_REINIT			"reason=multi_ap_wlan_reinit"			/* multi-ap wlan reinit. */
#define ENVP_MAP_AGENT_RESTART			"reason=multi_ap_agent_restart"			/* map_agent daemon restart */

/* Script name */
#define SCRIPT_MAP                  	"/var/multi_ap_script"  				/* script is generated by boa */

/* ************************************** */
/* Sync from user/boa/src/LINUX/options.h */
/* ************************************** */
//#define MAX_WLAN_VAP 4
//#define NUM_VWLAN_INTERFACE     (MAX_WLAN_VAP+1) // VAP+Repeater

/* ********************************** */
/* Sync from user/boa/src/LINUX/mib.h */
/* ********************************** */
typedef enum {
	WIFI_SEC_NONE = 0,
	WIFI_SEC_WEP = 1,
	WIFI_SEC_WPA = 2,
	WIFI_SEC_WPA2 = 4,
	WIFI_SEC_WPA2_MIXED = 6,
	WIFI_SEC_WAPI = 8,
	WIFI_SEC_WPA3 = 16,
	WIFI_SEC_WPA2_WPA3_MIXED = 20,
	WIFI_SEC_COUNT,
} WIFI_SECURITY_T;

typedef enum {
	ENCRYPT_DISABLED = 0,
	ENCRYPT_WEP = 1,
	ENCRYPT_WPA=2,
	ENCRYPT_WPA_TKIP = 2,
	ENCRYPT_WPA_AES = 3,
	ENCRYPT_WPA2=4,
	ENCRYPT_WPA2_AES = 4,
	ENCRYPT_WPA2_TKIP = 5,
	ENCRYPT_WPA2_MIXED = 6,
	ENCRYPT_WAPI = 7,
	ENCRYPT_WPA3 = 16,
	ENCRYPT_WPA3_MIXED = 20,
	ENCRYPT_COUNT,
} ENCRYPT_T;

typedef enum { PSK_FORMAT_PASSPHRASE = 0, PSK_FORMAT_HEX = 1 } PASK_FORMAT_T;
typedef enum { AP_MODE=0, CLIENT_MODE=1, WDS_MODE=2, AP_WDS_MODE=3, AP_MESH_MODE=4, MESH_MODE=5 } WLAN_MODE_T;
typedef enum { WPA_AUTH_AUTO=1, WPA_AUTH_PSK=2 } WPA_AUTH_T;
typedef enum { WPA_CIPHER_TKIP=1, WPA_CIPHER_AES=2, WPA_CIPHER_MIXED=3 } WPA_CIPHER_T;
enum { WSC_ENCRYPT_NONE=1, WSC_ENCRYPT_WEP=2, WSC_ENCRYPT_TKIP=4, WSC_ENCRYPT_AES=8, WSC_ENCRYPT_TKIPAES=12 };
enum { WSC_AUTH_OPEN=1, WSC_AUTH_WPAPSK=2, WSC_AUTH_SHARED=4, WSC_AUTH_WPA=8, WSC_AUTH_WPA2=0x10, WSC_AUTH_WPA2PSK=0x20, WSC_AUTH_WPA2PSKMIXED=0x22, WSC_AUTH_WPA3SAE=0x40, WSC_AUTH_WPA3WPA2MIXED=0x60 };

#if 0
/* ******************************************* */
/* Sync from user/boa/src/LINUX/subr_multiap.h */
/* ******************************************* */
typedef enum {
  MAP_SYNC_WLAN_ACL_DATA      = 0x01,
  MAP_SYNC_WLAN_SCHEDULE_DATA = 0x02
} MAP_SYNC_DATA_TYPE_T;

#define MAC_ADDR_LEN 6

struct acl_info {
        unsigned char acl_enable;
        unsigned char entry_num;
        unsigned char wlan_Idx;
        unsigned char vwlanIdx;
        unsigned char macAddr[MAC_ADDR_LEN];
};

struct wlan_schedule_info {
        unsigned char  wlan_Idx;
        unsigned char  enable;
        unsigned char  entry_num;
        unsigned char  mode;
        unsigned short eco;
        unsigned short fTime;
        unsigned short tTime;
        unsigned short day;
        unsigned int   inst_num;
};
#endif

/* ********************************** */
/* ********************************** */
#define MULTI_AP_TMP_CONFIG_FILE	"/tmp/multi_ap_config"
#define MULTI_AP_CONFIGURE_FILE		"/tmp/multi_ap_config_band"
#define MULTI_AP_REGDOMAIN_FILE		"/tmp/multi_ap_regdomain"
#define MULTI_AP_BAND0_CONFIG_FILE	"/tmp/multi_ap_band0_config"
#define MULTI_AP_BAND1_CONFIG_FILE	"/tmp/multi_ap_band1_config"
#define MULTI_AP_BAND2_CONFIG_FILE	"/tmp/multi_ap_band2_config"

#define READ_BUF_SIZE 50
char map_brif[READ_BUF_SIZE] = "br0"; //default bridge_name is br0

#if 0 //def EASYMESH_ISP_VENDOR_SYNC_SUPPORT
struct vendor_acl_info {
	unsigned char    acl_nr;
	struct acl_info *acl_data;
};

struct vendor_schedule_info {
	unsigned char    		   wlan_schedule_nr;
	struct wlan_schedule_info *wlan_schedule_data;
};

int change_mac_to_octe(char *str_mac, unsigned char *octe_mac)
{
	if(str_mac==NULL || octe_mac==NULL)
		return -1;

	int i, j;
	char tmp_str_mac[13]={0};

	for(i=0, j=0; i<17 && j<12; i++)
	{
		if(str_mac[i]!=':')
			tmp_str_mac[j++]=str_mac[i];
	}
	tmp_str_mac[12]=0;

	if (strlen(tmp_str_mac)==12 && rtk_string_to_hex(tmp_str_mac, octe_mac, 12))
		return 0;

	return -1;
}

#ifdef WLAN_VAP_ACL
#ifdef WLAN_ACL_FOR_MULTIAP
uint8_t _delall_wlan_acl_mib()
{
	int i = 0, j = 0, radio_idx = 0, entryNum = 0;
	MIB_CE_WLAN_AC_T acl_entry;

	for ( i = 0; i < NUM_WLAN_INTERFACE; i++ ){
		radio_idx  = i;
		entryNum   = mib_chain_total(MIB_WLAN_AC_TBL + radio_idx);
		for ( j = entryNum; j > 0; j-- ){
			memset(&acl_entry, 0, sizeof(MIB_CE_WLAN_AC_T));
			if ( !mib_chain_get(MIB_WLAN_AC_TBL + radio_idx, j-1, (void *)&acl_entry) ){
				printf("(%s) %d ERROR get wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
				return 0;
			}

			if ( acl_entry.wlanIdx != radio_idx )
				continue;

			if ( !mib_chain_delete(MIB_WLAN_AC_TBL + radio_idx, j-1) ) {
				printf("(%s) %d ERROR del wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
				return 0;
			}
		}
	}
	return 1;
}
#else
uint8_t _delall_wlan_acl_mib()
{
	int i = 0, j = 0, radio_idx = 0, entryNum = 0, k=0, vap_idx = 0;
	MIB_CE_WLAN_AC_T acl_entry;

	for ( i = 0; i < NUM_WLAN_INTERFACE; i++ ){
		for(k = 0; k < WLAN_MBSSID_NUM+1; k++){
			radio_idx  = i;
			vap_idx = k;
			entryNum   = mib_chain_total(MIB_WLAN_AC_TBL + radio_idx + WLAN_MIB_MAPPING_STEP*vap_idx);
			for ( j = entryNum; j > 0; j-- ){
				memset(&acl_entry, 0, sizeof(MIB_CE_WLAN_AC_T));
				if ( !mib_chain_get(MIB_WLAN_AC_TBL + radio_idx + WLAN_MIB_MAPPING_STEP*vap_idx, j-1, (void *)&acl_entry) ){
					printf("(%s) %d ERROR get wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
					return 0;
				}

				if ( acl_entry.wlanIdx != radio_idx )
					continue;

				if ( !mib_chain_delete(MIB_WLAN_AC_TBL + radio_idx + WLAN_MIB_MAPPING_STEP*vap_idx, j-1) ) {
					printf("(%s) %d ERROR del wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
					return 0;
				}
			}
		}
	}

	return 1;
}
#endif

uint8_t _set_wlan_acl_mib(struct acl_info acl_data)
{

	MIB_CE_MBSSIB_T wlan_entry;
	MIB_CE_WLAN_AC_T acl_entry;

	memset(&wlan_entry, 0, sizeof(MIB_CE_MBSSIB_T));
	if ( !mib_chain_get(MIB_MBSSIB_TBL + acl_data.wlan_Idx, acl_data.vwlanIdx, (void *)&wlan_entry) ){
		printf("(%s) %d ERROR get MBSSIB_TBL fail!\n",__FUNCTION__,__LINE__);
		return 0;
	}

	if (wlan_entry.acl_enable != acl_data.acl_enable) {
		wlan_entry.acl_enable = acl_data.acl_enable;
		if ( !mib_chain_update(MIB_MBSSIB_TBL + acl_data.wlan_Idx, (void *)&wlan_entry, acl_data.vwlanIdx) ) {
			printf("(%s) %d ERROR updata MBSSIB_TBL fail!\n",__FUNCTION__,__LINE__);
			return 0;
		}
	}

	if (acl_data.entry_num != 0) {
		memset(&acl_entry, 0, sizeof(MIB_CE_WLAN_AC_T));
		//set acl entry
		acl_entry.wlanIdx  =  acl_data.wlan_Idx;

#ifdef WLAN_ACL_FOR_MULTIAP
		acl_entry.vwlanIdx =  acl_data.vwlanIdx;
#endif
		memcpy(acl_entry.macAddr, acl_data.macAddr, MAC_ADDR_LEN);

#ifdef WLAN_ACL_FOR_MULTIAP
		if ( !mib_chain_add(MIB_WLAN_AC_TBL + acl_entry.wlanIdx, (void *)&acl_entry) )
#else
		if ( !mib_chain_add(MIB_WLAN_AC_TBL + acl_entry.wlanIdx+acl_data.vwlanIdx*WLAN_MIB_MAPPING_STEP, (void *)&acl_entry) )
#endif
		{
			printf("(%s) %d ERROR add wlan_ac_tbl fail!\n",__FUNCTION__,__LINE__);
			return 0;
		}
	}

	return 1;
}
#endif

#ifdef WLAN_SCHEDULE_SUPPORT
uint8_t _delall_wlan_schedule_mib()
{
	int i = 0, j = 0, radio_idx = 0, entryNum = 0;
	MIB_CE_SCHEDULE_T  schedule_entry;

	for ( i = 0; i < NUM_WLAN_INTERFACE; i++ ){
		radio_idx  = i;
		mib_get_s(MIB_WLAN_SCHEDULE_TBL_NUM+ radio_idx, (void *)&entryNum, sizeof(entryNum));
		for ( j = 0; j < entryNum; j++ ){
			memset(&schedule_entry, 0, sizeof(MIB_CE_SCHEDULE_T));
			if ( !mib_chain_get(MIB_WLAN_SCHEDULE_TBL + radio_idx, j, (void *)&schedule_entry) ){
				printf("(%s) %d ERROR get wlan_schedule_tbl fail\n",__FUNCTION__,__LINE__);
				return 0;
			}

			schedule_entry.eco   = 0;
			schedule_entry.fTime = 0;
			schedule_entry.tTime = 0;
			schedule_entry.day   = 0;
			schedule_entry.inst_num = 0;

			if ( !mib_chain_update(MIB_WLAN_SCHEDULE_TBL + radio_idx, (void *)&schedule_entry, j) ){
				printf("(%s) %d ERROR update wlan_schedule_tbl fail!\n",__FUNCTION__,__LINE__);
				return 0;
			}
		}
		entryNum = 0;
		mib_set(MIB_WLAN_SCHEDULE_TBL_NUM + radio_idx, (void *)&entryNum);
	}

	return 1;
}

uint8_t _set_wlan_schedule_mib(struct wlan_schedule_info schedule_data)
{
	int radio_idx = schedule_data.wlan_Idx;
	unsigned int enable = 0, entryNum = 0, mode = 0;
	MIB_CE_SCHEDULE_T  schedule_entry;

	mib_get_s(MIB_WLAN_SCHEDULE_ENABLED + radio_idx, (void *)&enable, sizeof(enable));
	mib_get_s(MIB_WLAN_SCHEDULE_TBL_NUM + radio_idx, (void *)&entryNum, sizeof(entryNum));
	mib_get_s(MIB_WLAN_SCHEDULE_MODE + radio_idx, (void *)&mode, sizeof(mode));

	if (enable != schedule_data.enable){
		enable = schedule_data.enable;
		mib_set(MIB_WLAN_SCHEDULE_ENABLED + radio_idx, (void *)&enable);
	}

	if (mode != schedule_data.mode){
		mode = schedule_data.mode;
		mib_set(MIB_WLAN_SCHEDULE_MODE + radio_idx, (void *)&mode);
	}

	if (schedule_data.entry_num == 0) {
		entryNum = schedule_data.entry_num;
		mib_set(MIB_WLAN_SCHEDULE_TBL_NUM + radio_idx, (void *)&entryNum);
	} else {
		memset(&schedule_entry, 0, sizeof(MIB_CE_SCHEDULE_T));
		if ( !mib_chain_get(MIB_WLAN_SCHEDULE_TBL + radio_idx, entryNum, &schedule_entry) ){
			printf("(%s) %d ERROR get wlan_schedule_tbl fail!\n",__FUNCTION__,__LINE__);
			return 0;
		}

		schedule_entry.eco      = schedule_data.eco;
		schedule_entry.fTime    = schedule_data.fTime;
		schedule_entry.tTime    = schedule_data.tTime;
		schedule_entry.day      = schedule_data.day;
		schedule_entry.inst_num = schedule_data.inst_num;

		if ( !mib_chain_update(MIB_WLAN_SCHEDULE_TBL + radio_idx, (void *)&schedule_entry, entryNum) ){
			printf("(%s) %d ERROR update wlan_schedule_tbl fail!\n",__FUNCTION__,__LINE__);
			return 0;
		}

		entryNum += 1;
		mib_set(MIB_WLAN_SCHEDULE_TBL_NUM + radio_idx, (void *)&entryNum);
	}

	return 1;
}
#endif

uint8_t process_rtk_vendor_spec_data(char *pchar, struct vendor_acl_info *vendor_acl_data, struct vendor_schedule_info *vendor_schedule_data, char *key)
{
	char *token=NULL, *token2=NULL, *savestr1=NULL, *savestr2=NULL, *char_tmp=NULL;
	int i=0;

	if (strcmp(key, "ACL") == 0){
		//process ACL payload
		token = strtok_r(pchar, ";", &savestr1);
		do {
			if (token == NULL){
				break;
			} else{
				i = vendor_acl_data->acl_nr =  vendor_acl_data->acl_nr + 1;
				vendor_acl_data->acl_data   =  (struct acl_info *)realloc(vendor_acl_data->acl_data, sizeof(struct acl_info) * i);

				token2 = strtok_r(token, " ", &savestr2);
				do{
					if (token2 == NULL){
						break;
					} else{
						if (strstr(token2, "wlan_Idx") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_acl_data->acl_data[i-1].wlan_Idx = atoi(char_tmp);
						}

						if (strstr(token2, "vwlanIdx") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_acl_data->acl_data[i-1].vwlanIdx = atoi(char_tmp);
						}

						if (strstr(token2, "acl_enable") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_acl_data->acl_data[i-1].acl_enable = atoi(char_tmp);
						}

						if (strstr(token2, "entry_num") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_acl_data->acl_data[i-1].entry_num = atoi(char_tmp);
						}

						if (strstr(token2, "macAddr") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							change_mac_to_octe(char_tmp, vendor_acl_data->acl_data[i-1].macAddr);
						}
					}
					token2 = strtok_r(NULL, " " , &savestr2);
				}while(token2 != NULL);
			}
			token = strtok_r(NULL, ";", &savestr1);
		}while(token != NULL);
	}else if(strcmp(key, "WLAN_SCHEDULE") == 0){
		//process WLAN_SCHEDULE payload
		token = strtok_r(pchar, ";", &savestr1);
		do {
			if (token == NULL){
				break;
			} else{
				i = vendor_schedule_data->wlan_schedule_nr =  vendor_schedule_data->wlan_schedule_nr + 1;
				vendor_schedule_data->wlan_schedule_data   =  (struct wlan_schedule_info *)realloc(vendor_schedule_data->wlan_schedule_data, sizeof(struct wlan_schedule_info) * i);

				token2 = strtok_r(token, " ", &savestr2);
				do{
					if (token2 == NULL){
						break;
					} else{
						if (strstr(token2, "wlan_Idx") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].wlan_Idx = atoi(char_tmp);
						}

						if (strstr(token2, "enable") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].enable = atoi(char_tmp);
						}

						if (strstr(token2, "entry_num") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].entry_num = atoi(char_tmp);
						}

						if (strstr(token2, "mode") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].mode = atoi(char_tmp);
						}

						if (strstr(token2, "eco") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].eco = atoi(char_tmp);
						}

						if (strstr(token2, "fTime") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].fTime = atoi(char_tmp);
						}

						if (strstr(token2, "tTime") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].tTime = atoi(char_tmp);
						}

						if (strstr(token2, "day") != NULL) {
							char_tmp  =  strchr(token2, ':');
							char_tmp  += 1;
							vendor_schedule_data->wlan_schedule_data[i-1].day = atoi(char_tmp);
						}

						if (strstr(token2, "inst_num") != NULL) {
							char_tmp  =  strchr(token2, ':');
	           				char_tmp  += 1;
	           				vendor_schedule_data->wlan_schedule_data[i-1].inst_num = atoi(char_tmp);
	           			}
					}
					token2 = strtok_r(NULL, " " , &savestr2);
				}while(token2 != NULL);
			}
			token = strtok_r(NULL, ";", &savestr1);
		}while(token != NULL);
	}

	return 0;
}

uint8_t _get_orig_vendor_data (struct vendor_acl_info *vendor_acl_data, struct vendor_schedule_info *vendor_schedule_data)
{
#if defined(WLAN_VAP_ACL) || defined(WLAN_SCHEDULE_SUPPORT)
	int i = 0, j = 0, radio_idx = 0, payload_idx = 0, entryNum = 0;
#endif
#if defined(WLAN_VAP_ACL) && !defined(WLAN_ACL_FOR_MULTIAP)
	int k = 0, vap_idx = 0;
#endif
#ifdef WLAN_VAP_ACL
	MIB_CE_MBSSIB_T    wlan_entry;
	MIB_CE_WLAN_AC_T   acl_entry;
#endif
#ifdef WLAN_SCHEDULE_SUPPORT
	int enable = 0, mode = 0;
	MIB_CE_SCHEDULE_T  schedule_entry;
#endif

	vendor_acl_data->acl_nr = 0;
#ifdef WLAN_VAP_ACL
#ifdef WLAN_ACL_FOR_MULTIAP
	for (i = 0; i < NUM_WLAN_INTERFACE; i++) {
		radio_idx  = i;
		entryNum = mib_chain_total(MIB_WLAN_AC_TBL + radio_idx);

		memset(&wlan_entry, 0, sizeof(MIB_CE_MBSSIB_T));
		if(!mib_chain_get(MIB_MBSSIB_TBL + radio_idx, 0, &wlan_entry)){
			printf("(%s) %d ERROR get MBSSIB_TBL fail!\n",__FUNCTION__,__LINE__);
			return 1;
		}

		if (entryNum == 0) {
			payload_idx = vendor_acl_data->acl_nr	+= 1;
			vendor_acl_data->acl_data = (struct acl_info *)realloc(vendor_acl_data->acl_data, sizeof(struct acl_info) * payload_idx);
			memset(&(vendor_acl_data->acl_data[payload_idx - 1]), 0, sizeof(struct acl_info));
			vendor_acl_data->acl_data[payload_idx - 1].wlan_Idx   = radio_idx;
			vendor_acl_data->acl_data[payload_idx - 1].acl_enable = wlan_entry.acl_enable;
			vendor_acl_data->acl_data[payload_idx - 1].entry_num  = entryNum;
		} else {
			for (j = 0; j < entryNum; j++) {
				payload_idx = vendor_acl_data->acl_nr   += 1;
				vendor_acl_data->acl_data = (struct acl_info *)realloc(vendor_acl_data->acl_data, sizeof(struct acl_info) * payload_idx);

				memset(&acl_entry, 0, sizeof(MIB_CE_WLAN_AC_T));
				if(!mib_chain_get(MIB_WLAN_AC_TBL + radio_idx, j, &acl_entry)){
					printf("(%s) %d ERROR get wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
					return 1;
				}
				memset(&(vendor_acl_data->acl_data[payload_idx - 1]), 0, sizeof(struct acl_info));
				vendor_acl_data->acl_data[payload_idx - 1].wlan_Idx   = acl_entry.wlanIdx;
				vendor_acl_data->acl_data[payload_idx - 1].vwlanIdx   = acl_entry.vwlanIdx;
				vendor_acl_data->acl_data[payload_idx - 1].acl_enable = wlan_entry.acl_enable;
				vendor_acl_data->acl_data[payload_idx - 1].entry_num  = entryNum;
				memcpy(vendor_acl_data->acl_data[payload_idx - 1].macAddr, acl_entry.macAddr, MACADDRLEN);
			}
		}
	}
#else
	for (i = 0; i < NUM_WLAN_INTERFACE; i++) {
		for(k = 0; k < WLAN_MBSSID_NUM+1; k++) {
			radio_idx  = i;
			vap_idx = k;
			entryNum = mib_chain_total(MIB_WLAN_AC_TBL + radio_idx + vap_idx*WLAN_MIB_MAPPING_STEP);

			memset(&wlan_entry, 0, sizeof(MIB_CE_MBSSIB_T));
			if(!mib_chain_get(MIB_MBSSIB_TBL + radio_idx, 0, &wlan_entry)){
				printf("(%s) %d ERROR get MBSSIB_TBL fail!\n",__FUNCTION__,__LINE__);
				return 1;
			}

			if (entryNum == 0) {
				payload_idx = vendor_acl_data->acl_nr	+= 1;
				vendor_acl_data->acl_data = (struct acl_info *)realloc(vendor_acl_data->acl_data, sizeof(struct acl_info) * payload_idx);


				memset(&(vendor_acl_data->acl_data[payload_idx - 1]), 0, sizeof(struct acl_info));
				vendor_acl_data->acl_data[payload_idx - 1].wlan_Idx   = radio_idx;
				vendor_acl_data->acl_data[payload_idx - 1].acl_enable = wlan_entry.acl_enable;
				vendor_acl_data->acl_data[payload_idx - 1].entry_num  = entryNum;
			} else {
				for (j = 0; j < entryNum; j++) {
					payload_idx = vendor_acl_data->acl_nr   += 1;
					vendor_acl_data->acl_data = (struct acl_info *)realloc(vendor_acl_data->acl_data, sizeof(struct acl_info) * payload_idx);

					memset(&acl_entry, 0, sizeof(MIB_CE_WLAN_AC_T));
					if(!mib_chain_get(MIB_WLAN_AC_TBL + radio_idx + vap_idx*WLAN_MIB_MAPPING_STEP, j, &acl_entry)){
						printf("(%s) %d ERROR get wlan_ac_tbl fail\n",__FUNCTION__,__LINE__);
						return 1;
					}
					memset(&(vendor_acl_data->acl_data[payload_idx - 1]), 0, sizeof(struct acl_info));
					vendor_acl_data->acl_data[payload_idx - 1].wlan_Idx   = acl_entry.wlanIdx;
					vendor_acl_data->acl_data[payload_idx - 1].vwlanIdx   = vap_idx;
					vendor_acl_data->acl_data[payload_idx - 1].acl_enable = wlan_entry.acl_enable;
					vendor_acl_data->acl_data[payload_idx - 1].entry_num  = entryNum;
					memcpy(vendor_acl_data->acl_data[payload_idx - 1].macAddr, acl_entry.macAddr, MACADDRLEN);
				}
			}
		}
	}
#endif
#endif

	vendor_schedule_data->wlan_schedule_nr = 0;
#ifdef WLAN_SCHEDULE_SUPPORT
	for (i = 0; i < NUM_WLAN_INTERFACE; i++) {
		radio_idx  = i;
		mib_get_s(MIB_WLAN_SCHEDULE_ENABLED + radio_idx, (void *)&enable,sizeof(enable));
		mib_get_s(MIB_WLAN_SCHEDULE_TBL_NUM + radio_idx, (void *)&entryNum,sizeof(entryNum));
		mib_get_s(MIB_WLAN_SCHEDULE_MODE + radio_idx, (void *)&mode, sizeof(mode));
		if (entryNum == 0) {
			payload_idx = vendor_schedule_data->wlan_schedule_nr += 1;
			vendor_schedule_data->wlan_schedule_data = (struct wlan_schedule_info *)realloc(vendor_schedule_data->wlan_schedule_data, sizeof(struct wlan_schedule_info) * payload_idx);

			memset(&(vendor_schedule_data->wlan_schedule_data[payload_idx - 1]), 0, sizeof(struct wlan_schedule_info));
			vendor_schedule_data->wlan_schedule_data[payload_idx - 1].wlan_Idx   = radio_idx;
			vendor_schedule_data->wlan_schedule_data[payload_idx - 1].enable     = enable;
			vendor_schedule_data->wlan_schedule_data[payload_idx - 1].entry_num  = entryNum;
			vendor_schedule_data->wlan_schedule_data[payload_idx - 1].mode       = mode;
		} else {
			for (j = 0; j < entryNum; j++) {
				payload_idx = vendor_schedule_data->wlan_schedule_nr += 1;
				vendor_schedule_data->wlan_schedule_data = (struct wlan_schedule_info *)realloc(vendor_schedule_data->wlan_schedule_data, sizeof(struct wlan_schedule_info) * payload_idx);

				memset(&schedule_entry, 0, sizeof(MIB_CE_SCHEDULE_T));
				if(!mib_chain_get(MIB_WLAN_SCHEDULE_TBL + radio_idx, j, &schedule_entry)){
					printf("(%s) %d Error get wlan_schedule_tbl!\n",__FUNCTION__,__LINE__);
					return 1;
				}
				memset(&(vendor_schedule_data->wlan_schedule_data[payload_idx - 1]), 0, sizeof(struct wlan_schedule_info));
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].wlan_Idx   = radio_idx;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].enable     = enable;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].entry_num  = entryNum;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].mode       = mode;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].eco        = schedule_entry.eco;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].fTime      = schedule_entry.fTime;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].tTime      = schedule_entry.tTime;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].day        = schedule_entry.day;
				vendor_schedule_data->wlan_schedule_data[payload_idx - 1].inst_num   = schedule_entry.inst_num;
			}
		}
	}
#endif

	return 0;
}

void _free_vendor_acl_data(struct vendor_acl_info *vendor_acl_data)
{
	if (vendor_acl_data->acl_data != NULL)
		free(vendor_acl_data->acl_data);
}

void _free_vendor_schedule_data(struct vendor_schedule_info *vendor_schedule_data)
{
	if (vendor_schedule_data->wlan_schedule_data != NULL)
		free(vendor_schedule_data->wlan_schedule_data);
}

#endif // EASYMESH_ISP_VENDOR_SYNC_SUPPORT


void _rtk_syscall_map_reload(char *interface_name)
{
	char *argv[] = {SCRIPT_MAP, interface_name, (char *)0};
	char *envp[] = {ENVP_MAP_RELOAD, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		//system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

void _rtk_syscall_map_configure(char *interface_name, char *config)
{
	char *argv[] = {SCRIPT_MAP, interface_name, config, (char *)0};
	char *envp[] = {ENVP_MAP_CONFIGURE, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		//system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

void _rtk_syscall_map_set_configured_band(char *band)
{
	char *argv[] = {SCRIPT_MAP, band, (char *)0};
	char *envp[] = {ENVP_MAP_SET_CONFIGURED_BAND, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

void _rtk_syscall_map_set_band(char *band, char *config)
{
	char *argv[] = {SCRIPT_MAP, band, config, (char *)0};
	char *envp[] = {ENVP_MAP_SET_BAND, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		//system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

void _rtk_syscall_map_wlan_reinit(void)
{
	char *argv[] = {SCRIPT_MAP, (char *)0};
	char *envp[] = {ENVP_MAP_WLAN_REINIT, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		//system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

void _rtk_syscall_map_agent_restart(void)
{
	char *argv[] = {SCRIPT_MAP, (char *)0};
	char *envp[] = {ENVP_MAP_AGENT_RESTART, (char *)0};
	char script[] = SCRIPT_MAP;
	int  pid = fork();

	if(pid < 0) {
		printf("[%s] fork() failed\n", __FUNCTION__);
	} else if(pid) {
		wait(0);
		printf("[%s] execve() done\n", __FUNCTION__);
	} else {
		//system("sleep 5");
		if(execve(script, argv, envp) < 0) {
			printf("[%s] execve() failed\n", __FUNCTION__);
			exit(0);
		}
	}
}

#define RTL8192CD_IOCTL_GET_MIB 0x89f2
uint8_t _rtk_get_mib(char *interfacename, char *mibname, void *result, int size)
{
	int          skfd;
	struct iwreq wrq;
	struct ifreq rq;
	char         tmp[100];

	skfd = socket(AF_INET, SOCK_DGRAM, 0);
	if (skfd < 0) {
		printf("ioctl [RTL8192CD_IOCTL_GET_MIB] socket error\n");
		return 0;
	}

	memset(&wrq, 0, sizeof(wrq));
	strcpy(wrq.ifr_name, interfacename);
	strcpy(tmp, mibname);

	wrq.u.data.pointer = tmp;
	wrq.u.data.length  = strlen(tmp);
	memcpy(&rq, &wrq, sizeof(struct iwreq));
	/* Do the request */
	if (ioctl(skfd, RTL8192CD_IOCTL_GET_MIB, &rq) < 0) {
		printf("ioctl [RTL8192CD_IOCTL_GET_MIB] for mib %s on %s failed!\n", mibname, interfacename);
		close(skfd);
		return 0;
	}

	if (size)
		memcpy(result, tmp, size);
	else
		strcpy(result, (char *)tmp);

	close(skfd);
	return 0;
}

uint8_t _is_interface_up(char *interface)
{
	int          skfd = 0;
	struct ifreq ifr;

	skfd = socket(AF_INET, SOCK_DGRAM, 0);
	if (skfd < 0) {
		printf("Failed to create socket...\n");
		return 0;
	}

	strncpy(ifr.ifr_name, interface, IFNAMSIZ - 1);

	if (ioctl(skfd, SIOCGIFFLAGS, &ifr) < 0) {
		close(skfd);
		return 0;
	}
	close(skfd);
	return (uint8_t) !!(ifr.ifr_flags & IFF_UP);
}

uint8_t _set_radio_band_width(int radio_band, int channel, int bandwidth, int sideband)
{
	printf("Setting radio_band %d: channel: %d, bandwidth: %d, sideband: %d\n", radio_band, channel, bandwidth, sideband);

	FILE *fp = NULL;
	char tmpbuf[256] = {0};
	char *config_file;

	if (radio_band == MAP_CONFIG_2G)
		config_file = MULTI_AP_BAND0_CONFIG_FILE;
	else if (radio_band == MAP_CONFIG_5GL)
		config_file = MULTI_AP_BAND1_CONFIG_FILE;
	else
		config_file = MULTI_AP_BAND2_CONFIG_FILE;

	fp = fopen(config_file, "w");

	if(fp == NULL) {
		printf("[ERROR] Can not open file %s.\n", config_file);
		return 1;
	}

	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_CHANNEL=%d\n", channel);
	fputs(tmpbuf, fp);

	if (bandwidth != -1) {
		snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_CHANNEL_BONDING=%d\n", bandwidth);
		fputs(tmpbuf, fp);
	}

	if (sideband != -1) {
		snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_CONTROL_BAND=%d\n", sideband);
		fputs(tmpbuf, fp);
	}

	fclose(fp);

	char radio_band_str[4] = {0};
	snprintf(radio_band_str, sizeof(radio_band_str), "%d", radio_band);

	_rtk_syscall_map_set_band(radio_band_str, config_file);

	return 0;
}

#if 0
uint8_t _get_configure_state()
{
	unsigned char configured_band;
	mib_get(MIB_MAP_CONFIGURED_BAND, (void *)&configured_band);
	printf("Configured band: %02x\n", configured_band);
	return (uint8_t)configured_band;
}
#endif

uint8_t _set_configure_state(uint8_t configure_state)
{
	int configured_state_int = (int)configure_state;
	char cmd[256]={0};

	snprintf(cmd, sizeof(cmd), "echo %d > %s", configured_state_int, MULTI_AP_CONFIGURE_FILE);
	system(cmd);

	char configured_state_str[4] = {0};
	snprintf(configured_state_str, sizeof(configured_state_str), "%d", configured_state_int);

	_rtk_syscall_map_set_configured_band(configured_state_str);

	return 0;
}

uint8_t _set_ap_mib(uint8_t radio_idx, char *interface_name, struct easymesh_interface_mib interface_mib)
{
	FILE *fp=NULL;
	int ret = 1;
	char tmpbuf[256]={0};
	char config_file_name[256] = {0};
	int val = 0;
	int mode = 0, bss_type = 0, hidessid = 0;
	int encrypt = 0, wsc_auth = 0, wsc_enc = 0, wsc_configured= 0, sha256 = 0, dotIEEE80211W = 0;
	int wpaAuth = 0, wpa2UnicastCipher = 0, unicastCipher = 0, wpaPSKFormat = 0;

	if (radio_idx > 2) {
		// Only support wlan0, wlan1 and wlan2
		printf("Unknown radio index %d\n", radio_idx);
		return 1;
	}

	if ((interface_mib.network_type != MULTI_AP_FRONTHAUL_BSS_BIT) && (interface_mib.network_type != MULTI_AP_BACKHAUL_BSS_BIT)) {
		printf("[%s %d] Not multi-ap bss, don't synchronize!\n", __FUNCTION__,__LINE__);
		return 1;
	}

	strcpy(config_file_name, MULTI_AP_TMP_CONFIG_FILE);
	strcat(config_file_name, "-");
	strcat(config_file_name, interface_name);
	fp = fopen(config_file_name, "w");
	if(fp == NULL) {
		printf("[ERROR] Can not open file %s.\n", config_file_name);
		return 0;
	}

	printf("[%s]Applying WSC configuration (%s), filename = %s: \n", __FUNCTION__, interface_name, config_file_name);
	printf("  - SSID            : %s\n", interface_mib.ssid);
	printf("  - NETWORK_KEY     : %s\n", interface_mib.network_key);
	printf("  - BSS_TYPE        : %02x\n", interface_mib.network_type);

	// tear down
	if (0 == interface_mib.is_enabled) {
		val = 1;
		snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_DISABLED=%d\n", val);
		fputs(tmpbuf, fp);
		printf("[WARNING] Disable radio [%s] with tear_down!\n", interface_name);
		//ret = 0; //check by sysconf
		goto end;
	}

	// interface enable
	val = 0;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_DISABLED=%d\n", val);
	printf("Enable Interface %s\n",interface_name);
	fputs(tmpbuf, fp);

	// Set SSID
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_SSID=\"%s\"\n", interface_mib.ssid);
	fputs(tmpbuf, fp);

	// Set PSK
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_PSK=\"%s\"\n", interface_mib.network_key);
	fputs(tmpbuf, fp);

	// Set WLAN MODE
	mode = AP_MODE;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_MODE=%d\n", mode);
	fputs(tmpbuf, fp);

	// Set BSS type
	bss_type = (int)interface_mib.network_type;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_MAP_BSS_TYPE=%d\n", bss_type);
	fputs(tmpbuf, fp);

	if (MULTI_AP_BACKHAUL_BSS_BIT == interface_mib.network_type) {
#ifndef RTK_MULTI_AP_WFA
		hidessid = 1;
#endif
		snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_HIDDEN_SSID=%d\n", hidessid);
		fputs(tmpbuf, fp);
	}

#ifdef WLAN_11W
		sha256        = 0;
		dotIEEE80211W = 0;
#endif
#ifdef WLAN_WPA3
	if (interface_mib.authentication_type == (AUTH_WPA2 | AUTH_WPA3)) {
		encrypt       = WIFI_SEC_WPA3 | WIFI_SEC_WPA2;
		wsc_auth      = WSC_AUTH_WPA3SAE | WSC_AUTH_WPA2PSK;
#ifdef WLAN_11W
		sha256        = 0;
		dotIEEE80211W = 1;
#endif
	} else if (interface_mib.authentication_type == AUTH_WPA3) {
		encrypt       = WIFI_SEC_WPA3;
		wsc_auth      = WSC_AUTH_WPA3SAE;
#ifdef WLAN_11W
		sha256        = 1;
		dotIEEE80211W = 2;
#endif
	} else if (interface_mib.authentication_type == (AUTH_WPA | AUTH_WPA2)) {
		encrypt       = WIFI_SEC_WPA2_MIXED;
		wsc_auth      = WSC_AUTH_WPA2PSKMIXED;
	} else {
		encrypt       = WIFI_SEC_WPA2;
		wsc_auth      = WSC_AUTH_WPA2PSK;

#ifdef RTK_MULTI_AP_WFA
		if (interface_mib.network_type & (MULTI_AP_FRONTHAUL_BSS_BIT | MULTI_AP_BACKHAUL_BSS_BIT)) {
#ifdef WLAN_11W
			dotIEEE80211W = 1;
#endif
		}
#endif
	}
#else
	encrypt       = ENCRYPT_WPA2;
	wsc_auth      = WSC_AUTH_WPA2PSK;

#ifdef RTK_MULTI_AP_WFA
	if (interface_mib.network_type & (MULTI_AP_FRONTHAUL_BSS_BIT | MULTI_AP_BACKHAUL_BSS_BIT)) {
#ifdef WLAN_11W
		dotIEEE80211W = 1;
#endif
	}
#endif
#endif //WLAN_WPA3
	wpa2UnicastCipher = WPA_CIPHER_AES;
	unicastCipher     = 0;
	wsc_enc = WSC_ENCRYPT_AES;
	if (!(interface_mib.network_type & MULTI_AP_BACKHAUL_BSS_BIT)) {
		if (interface_mib.authentication_type == (AUTH_WPA | AUTH_WPA2)) {
			encrypt           = WIFI_SEC_WPA2_MIXED;
			wsc_auth          = WSC_AUTH_WPA2PSKMIXED;
			wpa2UnicastCipher = WPA_CIPHER_MIXED;
			unicastCipher     = WPA_CIPHER_MIXED;
			wsc_enc           = WSC_ENCRYPT_TKIPAES;
		} else if (interface_mib.authentication_type == AUTH_WPA) {
			encrypt           = ENCRYPT_WPA;
			wsc_auth          = WSC_AUTH_WPAPSK;
			wsc_enc           = WSC_ENCRYPT_TKIP;
		} else if (interface_mib.authentication_type == AUTH_DISABLED){
			encrypt           = ENCRYPT_DISABLED;
			wsc_auth          = WSC_AUTH_OPEN;
			wsc_enc           = WSC_ENCRYPT_NONE;
		}
	}

#ifdef MULTI_AP_OPEN_ENCRYPT_SUPPORT
if (interface_mib.authentication_type == 1){
	encrypt       = ENCRYPT_DISABLED;
	wsc_auth      = WSC_AUTH_OPEN;
}
#endif
	wpaAuth           = WPA_AUTH_PSK;
#ifdef WLAN_WPA3
	if(encrypt & WIFI_SEC_WPA3)
	{
		wpa2UnicastCipher = WPA_CIPHER_AES;
		unicastCipher     = 0;
	}
	else
	{
		wpa2UnicastCipher = WPA_CIPHER_AES;
		unicastCipher     = WPA_CIPHER_AES;
	}
#else
	wpa2UnicastCipher = WPA_CIPHER_AES;
	unicastCipher     = WPA_CIPHER_AES;
#endif
	wpaPSKFormat      = 0; //PSK_FORMAT_PASSPHRASE

	// Set Encrypt
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_ENCRYPT=%d\n", encrypt);
	fputs(tmpbuf, fp);

	// Set Auth
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_AUTH=%d\n", wpaAuth);
	fputs(tmpbuf, fp);

	// Set WPA2 Cipher suite
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA2_CIPHER_SUITE=%d\n", wpa2UnicastCipher);
	fputs(tmpbuf, fp);

	// Set WPA Cipher suite
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_CIPHER_SUITE=%d\n", unicastCipher);
	fputs(tmpbuf, fp);

	// Set PSK_FORMAT_PASSPHRASE
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_PSK_FORMAT=%d\n", wpaPSKFormat);
	fputs(tmpbuf, fp);

	// Set dotIEEE80211W
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_DOTIEEE80211W=%d\n", dotIEEE80211W);
	fputs(tmpbuf, fp);

	// Set sha256
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_SHA256=%d\n", sha256);
	fputs(tmpbuf, fp);

	// Set WSC Auth
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_AUTH=%d\n", wsc_auth);
	fputs(tmpbuf, fp);

	// Set WSC Encrypt
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_ENC=%d\n", wsc_enc);
	fputs(tmpbuf, fp);

	// Set WSC PSK
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_PSK=\"%s\"\n", interface_mib.network_key);
	fputs(tmpbuf, fp);

	// Set WSC Configured
	wsc_configured = 1;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_CONFIGURED=\"%d\"\n", wsc_configured);
	fputs(tmpbuf, fp);

end:
	if(fp) fclose(fp);
	if(ret == 1)
	{
		_rtk_syscall_map_configure(interface_name, config_file_name);
	}

	return ret;
}

uint8_t _set_vxd_mib(uint8_t radio_idx, char *interface_name, struct easymesh_interface_mib interface_mib)
{
	FILE *fp=NULL;
	int ret = 1;
	char tmpbuf[256]={0};
	char buf[100];
	char config_file_name[256] = {0};
	int mode = 0, bss_type = 0;
	int encrypt = 0, wsc_auth = 0, wsc_enc = 0, wsc_configured= 0, sha256 = 0, dotIEEE80211W = 0;
	int wpaAuth = 0, wpa2UnicastCipher = 0, unicastCipher = 0, wpaPSKFormat = 0;

	if (radio_idx > 2) {
		// Only support wlan0, wlan1 and wlan2
		printf("Unknown radio index %d\n", radio_idx);
		return 1;
	}

	strcpy(config_file_name, MULTI_AP_TMP_CONFIG_FILE);
	strcat(config_file_name, "-");
	strcat(config_file_name, interface_name);
	fp = fopen(config_file_name, "w");
	if(fp == NULL) {
		printf("[ERROR] Can not open file %s.\n", config_file_name);
		return 0;
	}

	printf("[%s]Applying backhaul WSC configuration (%s), filename = %s: \n", __FUNCTION__, interface_name, config_file_name);
	printf("  - SSID            : %s\n", interface_mib.ssid);
	printf("  - NETWORK_KEY     : %s\n", interface_mib.network_key);
	printf("  - BSS_TYPE        : %02x\n", interface_mib.network_type);

	_rtk_get_mib(interface_name, "ssid", buf, 0);
	if (0 == strcmp(interface_mib.ssid, buf)) {
		_rtk_get_mib(interface_name, "passphrase", buf, 0);
		if (0 == strcmp(interface_mib.network_key, buf)) {
			printf("Setting is identical for interface %s, skip configuration\n", interface_name);
			ret = 2;
			goto end;
		}
	}

	// Set WLAN MODE
	mode = CLIENT_MODE;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_MODE=%d\n", mode);
	fputs(tmpbuf, fp);

	// Set SSID
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_SSID=\"%s\"\n", interface_mib.ssid);
	fputs(tmpbuf, fp);

	// Set BSS Type
	bss_type = MULTI_AP_BACKHAUL_STA_BIT;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_MAP_BSS_TYPE=%d\n", bss_type);
	fputs(tmpbuf, fp);

#ifdef WLAN_WPA3
	if (interface_mib.authentication_type == (AUTH_WPA2 | AUTH_WPA3)) {
		encrypt       = WIFI_SEC_WPA3 | WIFI_SEC_WPA2;
		wsc_auth      = WSC_AUTH_WPA3SAE | WSC_AUTH_WPA2PSK;
#ifdef WLAN_11W
		sha256        = 0;
		dotIEEE80211W = 1;
#endif
	} else if (interface_mib.authentication_type == AUTH_WPA3) {
		encrypt       = WIFI_SEC_WPA3;
		wsc_auth      = WSC_AUTH_WPA3SAE;
#ifdef WLAN_11W
		sha256        = 1;
		dotIEEE80211W = 2;
#endif
	} else {
		encrypt       = WIFI_SEC_WPA2;
		wsc_auth      = WSC_AUTH_WPA2PSK;
#ifdef WLAN_11W
		sha256        = 0;
		dotIEEE80211W = 0;
#endif

#ifdef RTK_MULTI_AP_WFA
		if (interface_mib.network_type & MULTI_AP_FRONTHAUL_BSS_BIT) {
#ifdef WLAN_11W
			dotIEEE80211W = 1;
#endif
		}
#endif
	}
#else
	encrypt       = ENCRYPT_WPA2;
	wsc_auth      = WSC_AUTH_WPA2PSK;
#ifdef WLAN_11W
	dotIEEE80211W = 0;
	sha256        = 0;
#endif
#ifdef RTK_MULTI_AP_WFA
	if (interface_mib.network_type & MULTI_AP_FRONTHAUL_BSS_BIT) {
#ifdef WLAN_11W
		dotIEEE80211W = 1;
#endif
	}
#endif
#endif //WLAN_WPA3
#ifdef MULTI_AP_OPEN_ENCRYPT_SUPPORT
	if(interface_mib.authentication_type == 1){
		encrypt       = ENCRYPT_DISABLED;
		wsc_auth      = WSC_AUTH_OPEN;
	}
#endif
	// Set Encrypt
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_ENCRYPT=%d\n", encrypt);
	fputs(tmpbuf, fp);

	// Set Auth
	wpaAuth = WPA_AUTH_PSK;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_AUTH=%d\n", wpaAuth);
	fputs(tmpbuf, fp);


#ifdef WLAN_WPA3
	if(encrypt & WIFI_SEC_WPA3)
	{
		wpa2UnicastCipher = WPA_CIPHER_AES;
		unicastCipher     = 0;
	}
	else
	{
		wpa2UnicastCipher = WPA_CIPHER_AES;
		unicastCipher     = WPA_CIPHER_AES;
	}
#else
	wpa2UnicastCipher = WPA_CIPHER_AES;
	unicastCipher     = WPA_CIPHER_AES;
#endif

	// Set WPA2 cipher suite
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA2_CIPHER_SUITE=%d\n", wpa2UnicastCipher);
	fputs(tmpbuf, fp);

	// Set WPA cipher suite
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_CIPHER_SUITE=%d\n", unicastCipher);
	fputs(tmpbuf, fp);

	// Set PSK_FORMAT_PASSPHRASE
	wpaPSKFormat = 0; //PSK_FORMAT_PASSPHRASE
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_PSK_FORMAT=%d\n", wpaPSKFormat);
	fputs(tmpbuf, fp);

	// Set PSK
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WPA_PSK=\"%s\"\n", interface_mib.network_key);
	fputs(tmpbuf, fp);

	// Set dotIEEE80211W
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_DOTIEEE80211W=%d\n", dotIEEE80211W);
	fputs(tmpbuf, fp);

	// Set sha256
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_SHA256=%d\n", sha256);
	fputs(tmpbuf, fp);

	// Set WSC auth
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_AUTH=%d\n", wsc_auth);
	fputs(tmpbuf, fp);

	// Set WSC enc
	wsc_enc = WSC_ENCRYPT_AES;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_ENC=%d\n", wsc_enc);
	fputs(tmpbuf, fp);

	// Set WSC configured
	wsc_configured = 1;
	snprintf(tmpbuf, sizeof(tmpbuf), "WLAN_WSC_CONFIGURED=\"%d\"\n", wsc_configured);
	fputs(tmpbuf, fp);

end:
	if(fp) fclose(fp);
	if(ret == 1)
	{
		_rtk_syscall_map_configure(interface_name, config_file_name);
	}

	return ret;
}

uint8_t _reload_setting(char *interfaces_name, uint8_t is_enabled)
{
	char cmd[128] = {0};

	if (NULL == strstr(interfaces_name, "wlan")) {
		return 1;
	}

	if (0 == _is_interface_up(interfaces_name) && !is_enabled) {
		return 2;
	}

	if(!is_enabled) {
		sprintf(cmd, "brctl delif %s %s; ifconfig %s down", map_brif, interfaces_name, interfaces_name);
		system(cmd);
		return 0;
	}

	_rtk_syscall_map_reload(interfaces_name);

	return 0;
}

#if 0
uint8_t _easymesh_set_vendor_data_mib()
{
#ifdef EASYMESH_ISP_VENDOR_SYNC_SUPPORT
	struct easymesh_datamodel easymesh_db;
	easymesh_db.configured_band  = 0;
	easymesh_db.radio_data_nr    = 0;
	easymesh_db.radio_data       = NULL;
	easymesh_db.per_radio_config = NULL;

	if (ini_parse("/var/multiap.conf", read_config_file, &easymesh_db) < 0) {
		printf("[RTK] Can't load configuration file!! \n");
		return INIT_ERROR_CONFIG_FILE;
	}

	// if (ini_parse("/var/multiap_mib.conf", read_mib_config_file, &easymesh_db) < 0) {
	// 	printf("[RTK] Can't load configuration file!! \n");
	// 	return INIT_ERROR_CONFIG_FILE;
	// }

	if (ini_parse("/var/multiap_setmib.conf", read_set_mib_config_file, &easymesh_db) < 0) {
		printf("[RTK] Can't load configuration file!! \n");
		return INIT_ERROR_CONFIG_FILE;
	}

	// set configure_state
	if (!mib_set(MIB_MAP_CONFIGURED_BAND, (void *)&easymesh_db.configured_band)) {
		printf("[ERROR] Cannot set configured band.\n");
		return 0;
	}

	int i = 0, j = 0;
#if defined(WLAN_VAP_ACL) || defined(WLAN_SCHEDULE_SUPPORT)
	int k = 0;
#endif
	struct vendor_acl_info  vendor_acl_data          = {0};
	struct vendor_schedule_info vendor_schedule_data = {0};

	vendor_acl_data.acl_nr                           = 0;
	vendor_acl_data.acl_data                         = NULL;
	vendor_schedule_data.wlan_schedule_nr	         = 0;
	vendor_schedule_data.wlan_schedule_data          = NULL;

	for(j = 0; j < easymesh_db.config_data_nr; j++){
		if (easymesh_db.per_radio_config[j].vendor_data_nr) {
			for (i = 0; i < easymesh_db.per_radio_config[j].vendor_data_nr; i++) {
				unsigned char *buffer	= (unsigned char *)malloc(easymesh_db.per_radio_config[j].vendor_datas[i].payload_len);
				char             *pchar = NULL;
				memcpy(buffer, easymesh_db.per_radio_config[j].vendor_datas[i].payload, easymesh_db.per_radio_config[j].vendor_datas[i].payload_len);

				if ((pchar=strstr((char *)buffer, "[ACL]"))!=NULL){
					pchar  =  strchr((char *)buffer, ']');
					pchar  += 1;
					process_rtk_vendor_spec_data(pchar, &vendor_acl_data, &vendor_schedule_data, "ACL");
				} else if ((pchar=strstr((char *)buffer, "[WLAN_SCHEDULE]"))!=NULL){
					pchar  =  strchr((char *)buffer, ']');
					pchar  += 1;
					process_rtk_vendor_spec_data(pchar, &vendor_acl_data, &vendor_schedule_data, "WLAN_SCHEDULE");
				}

				if (buffer)
					free(buffer);
			}
			break;
		}
	}

	int need_reinit = 0;
#if defined(WLAN_VAP_ACL) || defined(WLAN_SCHEDULE_SUPPORT)
	int match = 0;
#endif
	struct vendor_acl_info      orig_vendor_acl_data      = {0};
	struct vendor_schedule_info orig_vendor_schedule_data = {0};

	orig_vendor_acl_data.acl_nr                           = 0;
	orig_vendor_acl_data.acl_data                         = NULL;
	orig_vendor_schedule_data.wlan_schedule_nr            = 0;
	orig_vendor_schedule_data.wlan_schedule_data          = NULL;

	if ( vendor_acl_data.acl_nr || vendor_schedule_data.wlan_schedule_nr )
		_get_orig_vendor_data(&orig_vendor_acl_data, &orig_vendor_schedule_data);

#ifdef WLAN_VAP_ACL
	if (vendor_acl_data.acl_nr) {
		if (vendor_acl_data.acl_nr == orig_vendor_acl_data.acl_nr) {
			for (i = 0; i < vendor_acl_data.acl_nr; i++) {
				match = 0;
				for (j = 0; j < orig_vendor_acl_data.acl_nr; j++) {
					if ( (vendor_acl_data.acl_data[i].wlan_Idx == orig_vendor_acl_data.acl_data[j].wlan_Idx) && 
						 (vendor_acl_data.acl_data[i].acl_enable == orig_vendor_acl_data.acl_data[j].acl_enable) &&
						 (!memcmp(vendor_acl_data.acl_data[i].macAddr, orig_vendor_acl_data.acl_data[j].macAddr, MAC_ADDR_LEN))
					) {
						match = 1; //get a match
						break;
					}
				}
				if (!match) {
					break;
				}
			}
		} else {
			match = 0;
		}

		if (!match) {
			need_reinit |= MAP_SYNC_WLAN_ACL_DATA;
			//del all acl entry
			_delall_wlan_acl_mib();

			//sync vendor_acl_info to agent
			for(k = 0; k < vendor_acl_data.acl_nr; k++){
				_set_wlan_acl_mib(vendor_acl_data.acl_data[k]);
			}
			mib_update(CURRENT_SETTING,CONFIG_MIB_ALL);
		}
	}
#endif

#ifdef WLAN_SCHEDULE_SUPPORT
	if (vendor_schedule_data.wlan_schedule_nr) {
		if (vendor_schedule_data.wlan_schedule_nr == orig_vendor_schedule_data.wlan_schedule_nr) {
			for (i = 0; i < vendor_schedule_data.wlan_schedule_nr; i++) {
				match = 0;
				for (j = 0; j < orig_vendor_schedule_data.wlan_schedule_nr; j++) {
					if ( (vendor_schedule_data.wlan_schedule_data[i].wlan_Idx == orig_vendor_schedule_data.wlan_schedule_data[j].wlan_Idx) && 
						 (vendor_schedule_data.wlan_schedule_data[i].enable == orig_vendor_schedule_data.wlan_schedule_data[j].enable) &&
						 (vendor_schedule_data.wlan_schedule_data[i].mode == orig_vendor_schedule_data.wlan_schedule_data[j].mode) &&
						 (vendor_schedule_data.wlan_schedule_data[i].eco == orig_vendor_schedule_data.wlan_schedule_data[j].eco) &&
						 (vendor_schedule_data.wlan_schedule_data[i].fTime == orig_vendor_schedule_data.wlan_schedule_data[j].fTime) &&
						 (vendor_schedule_data.wlan_schedule_data[i].tTime == orig_vendor_schedule_data.wlan_schedule_data[j].tTime) &&
						 (vendor_schedule_data.wlan_schedule_data[i].day == orig_vendor_schedule_data.wlan_schedule_data[j].day)
					) {
						match = 1; //get a match
						break;
					}
				}
				if (!match) {
					break;
				}
			}
		}else {
			match = 0;
		}

		if (!match) {
			need_reinit |= MAP_SYNC_WLAN_SCHEDULE_DATA;
			//del all wlan_schedule entry
			_delall_wlan_schedule_mib();

			//sync vendor_acl_info to agent
			for(k = 0; k < vendor_schedule_data.wlan_schedule_nr; k++){
				_set_wlan_schedule_mib(vendor_schedule_data.wlan_schedule_data[k]);
			}
			mib_update(CURRENT_SETTING,CONFIG_MIB_ALL);
		}
	}
#endif

	_free_vendor_acl_data(&vendor_acl_data);
	_free_vendor_acl_data(&orig_vendor_acl_data);
	_free_vendor_schedule_data(&vendor_schedule_data);
	_free_vendor_schedule_data(&orig_vendor_schedule_data);

	return need_reinit;
#else
	return 0;
#endif
}
#endif

uint8_t _easymesh_set_mib()
{
	int                       i, j;
	struct easymesh_datamodel easymesh_db = {0};
	easymesh_db.configured_band  = 0;
	easymesh_db.radio_data_nr    = 0;
	easymesh_db.radio_data       = NULL;
	easymesh_db.per_radio_config = NULL;

	int radio_idx = 0;

	if (ini_parse("/var/multiap.conf", read_config_file, &easymesh_db) < 0) {
		printf("[RTK] Can't load configuration file!! \n");
		return INIT_ERROR_CONFIG_FILE;
	}

	// if (ini_parse("/var/multiap_mib.conf", read_mib_config_file, &easymesh_db) < 0) {
	// 	printf("[RTK] Can't load configuration file!! \n");
	// 	return INIT_ERROR_CONFIG_FILE;
	// }

	if (ini_parse("/var/multiap_setmib.conf", read_set_mib_config_file, &easymesh_db) < 0) {
		printf("[RTK] Can't load configuration file!! \n");
		return INIT_ERROR_CONFIG_FILE;
	}

	if (easymesh_db.bridge_name)
		snprintf(map_brif, sizeof(map_brif), "%s", easymesh_db.bridge_name);

	#if 0
	// set configure_state
	if (!mib_set(MIB_MAP_CONFIGURED_BAND, (void *)&easymesh_db.configured_band)) {
		printf("[ERROR] Cannot set configured band.\n");
		return 0;
	}
	#endif

	// set configure_state
	int configured_state_int = (int)easymesh_db.configured_band;
	_set_configure_state(configured_state_int);

	// set channel & bonding

	// set mib
	int radio_band, interface_index;

	char *radio_name = NULL;

	char interface_name[15] = {0};

	for (i = 0; i < easymesh_db.radio_data_nr; i++) {
		radio_band = easymesh_db.radio_data[i].radio_band;
		if (MAP_CONFIG_2G == radio_band) {
			radio_name = easymesh_db.radio_name_24g;
		} else if (MAP_CONFIG_5GL == radio_band) {
			radio_name = easymesh_db.radio_name_5gl;
		} else if (MAP_CONFIG_5GH == radio_band) {
			radio_name = easymesh_db.radio_name_5gh;
		} else {
			printf("Unsupported band %02x!\n", radio_band);
			continue;
		}

		radio_idx = radio_name[4] - '0';

		if (easymesh_db.radio_data[i].need_change_channel) {
			//_set_radio_band_width(radio_idx, easymesh_db.radio_data[i].radio_channel,  easymesh_db.radio_data[i].channel_bandwidth, 0);
			_set_radio_band_width(radio_band, easymesh_db.radio_data[i].radio_channel,  easymesh_db.radio_data[i].channel_bandwidth, 0);
		}
		for (j = 0; j < easymesh_db.radio_data[i].interface_nr; j++) {
			interface_index = easymesh_db.radio_data[i].interface_mib[j].interface_index;
			//if (NUM_VWLAN_INTERFACE == interface_index) {
			if (easymesh_db.max_bss_per_radio == interface_index) {
#ifndef RTK_MULTI_AP_WFA
				if (1 == easymesh_db.radio_data[i].interface_mib[j].need_configure) {
					sprintf(interface_name, "%s-vxd", radio_name);
					_set_vxd_mib(radio_idx, interface_name, easymesh_db.radio_data[i].interface_mib[j]);
					_reload_setting(interface_name, easymesh_db.radio_data[i].interface_mib[j].is_enabled);
				}
#endif
			} else {
				if (1 == easymesh_db.radio_data[i].interface_mib[j].need_configure) {
					if (0 == j) {
						// root ap
						sprintf(interface_name, "%s", radio_name);
					} else {
						// vap
						sprintf(interface_name, "%s-%s%d", radio_name, easymesh_db.vap_prefix, j - 1);
					}
					_set_ap_mib(radio_idx, interface_name, easymesh_db.radio_data[i].interface_mib[j]);
					_reload_setting(interface_name, easymesh_db.radio_data[i].interface_mib[j].is_enabled);
				}
			}
		}
	}

	return 1;
}

int main(int argc, char *argv[])
{
	int c;
	int reinit = 0;
	int band = -1, cur_channel = -1, bandwidth = -1, sideband = -1;
	int configured_band = 0;

	while ((c = getopt(argc, argv, "rflvb:c:ta")) != -1) {
		switch (c) {
		case 'f': {
			reinit = FULL_RELOAD;
			break;
		}
		case 'r': {
			reinit = MIB_RELOAD;
			break;
		}
		case 'l': {
			reinit = SOFT_RELOAD;
			break;
		}
		case 'v': {
			reinit = VENDOR_DATA_RELOAD;
			break;
		}
		case 'b': {
			char *token, *saveptr = NULL;
			int * band_str = NULL;
			int   str_num = 0, i = 0;
			for (token = (char *)optarg;; token = NULL) {
				token = strtok_r(token, "_", &saveptr);
				if (NULL == token)
					break;
				i++;
				band_str          = (int *)realloc(band_str, i * sizeof(int));
				band_str[str_num] = atoi(token);
				str_num += 1;
			}
			if( 2 == str_num) {
				band        = band_str[0];
				cur_channel = band_str[1];
			} else if (4 == str_num) {
				band        = band_str[0];
				cur_channel = band_str[1];
				bandwidth   = band_str[2];
				sideband    = band_str[3];
			} else {
				printf("wrong cmd for map_reinit daemon!!!!\n");
				free(band_str);
				return 0;
			}
			reinit = BAND_MIB_SET;
			free(band_str);
			break;
		}
		case 'c': {
			if (optarg) {
				configured_band = atoi(optarg);
			}
			reinit = CONFIG_STATE_SET;
			break;
		}
		case 't': {
			reinit = TEST_RELOAD;
			break;
		}
		case 'a': {
			reinit = AGENT_RESTART;
			break;
		}

		}
	}

	if (TEST_RELOAD == reinit) {
		_rtk_syscall_map_wlan_reinit(); //map_restart_wlan();
	} else if (FULL_RELOAD == reinit) {
		system("killall map_checker; echo 1 > /tmp/map_checker_end.txt");
		_easymesh_set_mib();
		//_easymesh_set_vendor_data_mib();
		printf("\nNeed full reload!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
		_rtk_syscall_map_wlan_reinit(); //map_restart_wlan();
	} else if (SOFT_RELOAD == reinit) {
		system("killall map_checker; echo 1 > /tmp/map_checker_end.txt");
		_easymesh_set_mib();
		//_easymesh_set_vendor_data_mib();
		printf("\nOnly need reload!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
		_rtk_syscall_map_wlan_reinit(); //map_restart_wlan();
	} else if (VENDOR_DATA_RELOAD == reinit) {
#if 0
		int ret = 0;
		ret = _easymesh_set_vendor_data_mib();
		if (ret & MAP_SYNC_WLAN_ACL_DATA) {
			printf("\nNeed vendor data reload!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
			system("killall map_checker; echo 1 > /tmp/map_checker_end.txt");
			char command[64];
			sprintf(command, "killall map_agent");
			system(command);
			map_restart_wlan();
		} else if (ret & MAP_SYNC_WLAN_SCHEDULE_DATA) {
#ifdef WLAN_SCHEDULE_SUPPORT
			printf("\nRestart wlan schedule only!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
			restartWlanSchedule();
#endif
		} else {
			printf("\nAll vendor data received is identical to the original, skip re-init!!!!\n");
		}
#endif
	} else if (BAND_MIB_SET == reinit) {
		struct easymesh_datamodel easymesh_db = { 0 };
		//char *                    radio_name = NULL;
		if (ini_parse("/var/multiap.conf", read_config_file, &easymesh_db) < 0) {
			printf("[RTK] Can't load configuration file!! \n");
			return INIT_ERROR_CONFIG_FILE;
		}
		if (MAP_CONFIG_2G == band) {
			//radio_name = easymesh_db.radio_name_24g;
		} else if (MAP_CONFIG_5GL == band) {
			//radio_name = easymesh_db.radio_name_5gl;
			sideband = 0; // Auto
		} else if (MAP_CONFIG_5GH == band) {
			//radio_name = easymesh_db.radio_name_5gh;
			sideband = 0; // Auto
		} else {
			printf("Unsupported band %02x!\n", band);
			return 1;
		}
		//int radio_idx = radio_name[4] - '0';
		//_set_radio_band_width(radio_idx, cur_channel, bandwidth, sideband);
		_set_radio_band_width(band, cur_channel, bandwidth, sideband);
	} else if (CONFIG_STATE_SET == reinit) {
		_set_configure_state(configured_band);
	} else if (MIB_RELOAD == reinit) {
#if 0
		struct mib_info mib_data = { 0 };
		map_read_mib_to_config(&mib_data);
		map_write_mib_data(&mib_data, "/var/multiap_mib.conf");
		map_free_mib_data(&mib_data);
#endif
	} else if (AGENT_RESTART) {
		printf("[RTK] Reastart map_agent daemon...\n");
		_rtk_syscall_map_agent_restart();
	}

	return 0;
}
